### ISSUE TITLE
x509-cert: Generate certificate signing request?

### ISSUE THREAD

**Issue by jstayton** [RustCrypto/formats#1031]
👋🏻 Thanks for the great work you're doing here!

I'm wondering if the `x509-cert` crate is able to generate a certificate signing request at this point? I know development is pretty early on it. The [tests](https://github.com/RustCrypto/formats/blob/master/x509-cert/tests/certreq.rs) seem to be focused on reading/modeling an existing CSR.

Any pointers/examples would be much appreciated. Thanks!

**Comment by baloo** [comment]
Hey! thanks for raising the issue.
Certificate requests were not on my mind when I pushed the initial draft of the certificate builder. A request builder is not too hard to add, although I needed to redesign a bit the `AsExtension` trait.
I sent a rough draft on https://github.com/RustCrypto/formats/pull/1034, would love to get your feedback and opinion.

**Comment by jstayton** [comment]
Hey @baloo – Wow, that's great news! I appreciate your work.

I'm new to Rust, so I could definitely be missing something obvious here, but when I try to run your example/test code in  a new crate, I get this:

```
error[E0277]: the trait bound `sha2::OidSha256: AssociatedOid` is not satisfied
   --> src/main.rs:26:52
    |
26  |     let mut builder = RequestBuilder::new(subject, &signer).unwrap();
    |                       -------------------          ^^^^^^^ the trait `AssociatedOid` is not implemented for `sha2::OidSha256`
    |                       |
    |                       required by a bound introduced by this call
    |
    = help: the following other types implement trait `AssociatedOid`:
              AuthorityInfoAccessSyntax
              AuthorityKeyIdentifier
              BaseCrlNumber
              BasicConstraints
              CertificatePolicies
              CoreWrapper<T>
              CrlDistributionPoints
              CrlNumber
            and 19 others
    = note: required for `CtVariableCoreWrapper<sha2::core_api::Sha256VarCore, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, sha2::OidSha256>` to implement `AssociatedOid`
    = note: 2 redundant requirements hidden
    = note: required for `ecdsa::Signature<NistP256>` to implement `AssociatedOid`
    = note: required for `ecdsa::Signature<NistP256>` to implement `AssociatedAlgorithmIdentifier`
    = note: required for `ecdsa::signing::SigningKey<NistP256>` to implement `SignatureAlgorithmIdentifier`
    = note: required for `ecdsa::signing::SigningKey<NistP256>` to implement `DynSignatureAlgorithmIdentifier`
note: required by a bound in `RequestBuilder::<'s, S>::new`
   --> /Users/jstayton/.cargo/git/checkouts/formats-74870079c31416c0/c33f1f0/x509-cert/src/builder.rs:366:18
    |
366 |     S: Keypair + DynSignatureAlgorithmIdentifier,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `RequestBuilder::<'s, S>::new`
```

**Comment by baloo** [comment]
I think you're missing the features on your dependencies.
That should look something like that in your `Cargo.toml`:
```
ecdsa = { version = "0.16.4", features = ["digest", "pem"] }
sha2 = { version = "0.10", features = ["oid"] }
```

**Comment by jstayton** [comment]
Aha, that was it. Thanks for the quick reply! Like I said, new to this. 😅

It works great for my use case!

**Comment by juliankrieger** [comment]
@baloo unfortunately, I'm getting the same error and I'm having trouble getting this to work. I've activated both features, but I still seem like I'm missing something. Are there some trait imports that need to be done?

**Comment by baloo** [comment]
We're in the middle of bumping pre-releases dependencies again. This is a mine field at the moment.
Whatever I could provide you would be broken a few hours/days later.

If you could please raise this again in a week or so.

**Comment by juliankrieger** [comment]
How about raising this 9 Months from then? D:

**Comment by baloo** [comment]
@juliankrieger the feature is usable from x509-cert 0.2.2
