### ISSUE TITLE
x509-cert: support for BMPString? (unknown/unsupported ASN.1 DER tag: 0x1e at DER byte xxx)

### ISSUE THREAD

**Issue by CBenoit** [RustCrypto/formats#1036]
Hi!

It seems that otherwise "valid" certificates are unsupported by `x509-cert`.

[Here is a sample](https://lapo.it/asn1js/#MIIEWTCCA0WgAwIBAgIFAQAAAAIwCQYFKw4DAh0FADARMQ8wDQYDVQQDEwZCZWNrZXIwHhcNMTkxMDI2MjMyNjQ1WhcNMzgwMTE5MDMxNDA3WjCBpjGBozAnBgNVBAMeIABuAGMAYQBjAG4AXwBpAHAAXwB0AGMAcAA6ADEAMgA3MDMGA1UEBx4sAG4AYwBhAGMAbgBfAGkAcABfAHQAYwBwADoAMQAyADcALgAwAC4AMAAuADEwQwYDVQQFHjwAMQBCAGMASwBlAFYAMwBNAGcAdABqAFUAdABvADIAUABJAGgANQBSAFcAVgA2AEIAWABIAHcAPQANAAowWDAJBgUrDgMCDwUAA0sAMEgCQQCrrIcRg7_pSCUALDMxXj14yF-CyzZB9bRlFe4EMa7iSFiZf0-QHfd81_hHk6DKnN-RsEHoBUvcJFty92iRhPsZAgMBAAGjggH0MIIB8DAUBgkrBgEEAYI3EgQBAf8EBAEABQAwPAYJKwYBBAGCNxICAQH_BCxNAGkAYwByAG8AcwBvAGYAdAAgAEMAbwByAHAAbwByAGEAdABpAG8AbgAAADCB3QYJKwYBBAGCNxIFAQH_BIHMADAAAAEAAAACAAAAIgQAABwASgBmAEoAsAADADMAZAAyADYANwA5ADUANAAtAGUAZQBiADcALQAxADEAZAAxAC0AYgA5ADQAZQAtADAAMABjADAANABmAGEAMwAwADgAMABkAAAAMwBkADIANgA3ADkANQA0AC0AZQBlAGIANwAtADEAMQBkADEALQBiADkANABlAC0AMAAwAGMAMAA0AGYAYQAzADAAOAAwAGQAAAAAAAAAAICAAAAAABAAgIAAAAAAAACAgAAAAAAAMIGABgkrBgEEAYI3EgYBAf8EcAAwAAAAACAAUABXAEkATgAtADQATAA0AEwANgBBAE0AQgBDAFMAUQAAADAAMAA0ADIAOQAtADAAMAAwADAAMAAtADMANAA5ADcAMgAtAEEAVAAzADUAMwAAAFcATwBSAEsARwBSAE8AVQBQAAAAAAAwNwYDVR0jAQH_BC0wK6EipCBXAEkATgAtADQATAA0AEwANgBBAE0AQgBDAFMAUQAAAIIFAQAAAAIwCQYFKw4DAh0FAAOCAQEAPtPVYYqHe5gsbSA4EgjY94MI-Oay4SHhMGESGejBQa9ZfB4-yECeJOiNDEH9-D6hs6xWrFKRWvjQQI4TR6mKCmJtEYkgVufWXxJElL9jmaNCQNXGjB9L-K-DjvZ0sgtVE0p27TfYPRPnrkNMmmFsexvRqgCX31uFn8jubOWiY3bkBtMq4FXhknjtA3t9Gm7CVtytbtep_qf9CQqm1YqZpHWJrYTHCfdMbtDigBdi-ob-Q1HytPbvO7M9H--jy6JXJXwC8icch3COhCD-HUrEhyQ7uv80GuL_okM52BmX-PD5c6a2VWSmyqNIIrcam5gaji-q7MH-JTYrcJeMW2Ihww):
```
unknown/unsupported ASN.1 DER tag: 0x1e at DER byte 186
```

Likewise with [this other sample](https://lapo.it/asn1js/#MIIE-TCCA-WgAwIBAgIFAQAAAAIwCQYFKw4DAh0FADAyMTAwEwYDVQQDHgwAUgBPAEQARQBOAFQwGQYDVQQHHhIAVwBPAFIASwBHAFIATwBVAFAwHhcNMDcwNTI2MTI0NTUzWhcNMzgwMTE5MDMxNDA3WjCBkjGBjzAjBgNVBAMeHABuAGMAYQBsAHIAcABjADoAUgBPAEQARQBOAFQwIwYDVQQHHhwAbgBjAGEAbAByAHAAYwA6AFIATwBEAEUATgBUMEMGA1UEBR48ADEAQgBjAEsAZQBiAGgAcABYAFoAdABMAHEATwA3AFMAUQBuAEIAcABSAGYAdQBkAGQAZABZAD0ADQAKMIIBHjAJBgUrDgMCDwUAA4IBDwAwggEKAoIBAQDIkGvwxliBpokcDvL22YIScaVuUdvgMmaqkXcOiKtEt9OX2niPDkQmRn8W1MZj68pV5U6LLaZtg5WnqGr60L4mgK6rCmSQMozfXPj50H7Razopfn29AqOGbP2lNXHaIbTupJfzqLIS26QnVzbJCCJcVPeZe6MvuFzVFrgZJ2txlxRb6B8j6Fy4G3NLbnoDE_-X6WK5SqBRI8NsMj4C8mOXIxzFeNj8twdLsFYPdN_FVijklv0gjmVa5kXtwQU-q1hVQK_iR6BMSaONOeNmX5MzbfhfxVTl-1c63kUStccFS4gftDUPfMB1F8Zn3UiAywq-nfaTYGU065evZW3fv29bAgMBAAGjggG_MIIBuzAUBgkrBgEEAYI3EgQBAf8EBAEABQAwPAYJKwYBBAGCNxICAQH_BCxNAGkAYwByAG8AcwBvAGYAdAAgAEMAbwByAHAAbwByAGEAdABpAG8AbgAAADCBzQYJKwYBBAGCNxIFAQH_BIG8ADAAAAEAAAACAAAACQQAABwASgBmAEoAsAABADMAZAAyADYANwA5ADUANAAtAGUAZQBiADcALQAxADEAZAAxAC0AYgA5ADQAZQAtADAAMABjADAANABmAGEAMwAwADgAMABkAAAAMwBkADIANgA3ADkANQA0AC0AZQBlAGIANwAtADEAMQBkADEALQBiADkANABlAC0AMAAwAGMAMAA0AGYAYQAzADAAOAAwAGQAAAAAAAAQAIBkAAAAAAAwbgYJKwYBBAGCNxIGAQH_BF4AMAAAAAAOAD4AUgBPAEQARQBOAFQAAAA3ADgANAA0ADAALQAwADAANgAtADUAOAA2ADcAMAA0ADUALQA3ADAAMwA0ADcAAABXAE8AUgBLAEcAUgBPAFUAUAAAAAAAMCUGA1UdIwEB_wQbMBmhEKQOUgBPAEQARQBOAFQAAACCBQEAAAACMAkGBSsOAwIdBQADggEBAC7rxw24HUcRnQmIm1HcRd1WUeLRIxE5my3ax_5614TjPVR3l00ZkjBkoEfGL22T0mR8dsgmRa1aRFTq9ksodx936ux0AjhonnkUcoM0dGLSwQykC_KpsDi7fNCuvr90RxagotP8Hbm6JhAG77odQwFOTm9WyuDu0PlOpmJj_9oLyRVhbO1rC8RYU4YPjAwaLt_B8kNI1K8KeDayUTIobMJ1eT9umWaIPjTTf22dB-Rr64TiCrvKfTpAcbC-R58SWDFhK5tKmkmP5bQM9QRNPM680nkV2Sj0I1Z3nzhkPgOIkgQmdrm13xnQeEt6YEAjkfEVIiu05wJUqRYhW2CWqVw):
```
unknown/unsupported ASN.1 DER tag: 0x1e at DER byte 80
```

The byte position in the error looks a bit off, but I suspect the problem comes from the BMPString. I know this string type is advised against, but they can do appear in the wild.

**Comment by tarcieri** [comment]
Dup of #154
