### ISSUE TITLE
`cms` and `pkcs7` overlap

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/formats#1045]
The `cms` and `pkcs7` crates seem to have a lot of overlap.

Should we pick one to be the place for CMS-related functionality and retire the other?

cc @carl-wallace

**Comment by carl-wallace** [comment]
Possibly. The cms crate is more complete with regard to CMS structures. I prefer how ContentInfo is handled there as well (unsurprisingly). The cms crate more consistent with how structures are defined in x509, ocsp, cmpv2 and crmf. The pkcs7 crate may predate x509, which is when lots of stuff was added to der. The pkcs7 crate is mostly SignedData focused. Not sure offhand how much the structures other than ContentInfo differ.

**Comment by tarcieri** [comment]
I added a deprecation notice to `pkcs7` in #1062.

Let's use `cms` as the basis for all work on Cryptographic Message Syntax.
