### ISSUE TITLE
How to use external crates that re-exports `der` and derive macros from `der`?

### ISSUE THREAD

**Issue by RaitoBezarius** [RustCrypto/formats#1107]
It seems like re-exporting `der` from other crates prevent from mixing traits implementations properly.

For example, I am defining:
```rust
/// SPC_INDIRECT_DATA_OBJID http://oid-info.com/get/1.3.6.1.4.1.311.2.1.4
pub const SPC_INDIRECT_DATA_OBJID: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.3.6.1.4.1.311.2.1.4");

#[derive(Clone, Debug, Eq, PartialEq, Sequence)]
pub struct DigestInfo<'a> {
    // Technically: RFC3279 only?
    // Not updates, or is it?
    pub digest_algorithm: AlgorithmIdentifier<AnyRef<'a>>,
    pub digest: OctetStringRef<'a>,
}

#[derive(Clone, Debug, Eq, PartialEq, ValueOrd, Sequence)]
struct SpcAttributeTypeAndOptionalValue {
    pub content_type: ObjectIdentifier,
    #[asn1(context_specific = "0", tag_mode = "EXPLICIT")]
    pub value: Any,
}

#[derive(Clone, Debug, Eq, PartialEq, Sequence)]
struct SpcIndirectDataContent<'a> {
    pub data: SpcAttributeTypeAndOptionalValue,
    pub message_digest: DigestInfo<'a>
}
```

and I have `cms` / `x509_cert` in my project, but not `der`, the `Sequence` deriver will fail with `could not find der in the list of imported crates`.

If I import `der`, then, I have to use all its traits for my stuff, and then I cannot reuse `x509_cert` existing structures.

Am I holding this wrong?

cc @baloo (it's for `goblin-signing`)

**Comment by RaitoBezarius** [comment]
I am wondering if the fix is not just removing `::der` and using `der` and letting me bind `der` properly by reusing the export.

**Comment by RaitoBezarius** [comment]
Okay, apparently, the solution is `extern create self as der;` in `der/src/lib.rs`: https://users.rust-lang.org/t/how-to-express-crate-path-in-procedural-macros/91274/10

**Comment by baloo** [comment]
I'm confused about the "have to use all its traits" comment you're making. If it's the same version as the one x509_cert uses it's not an issue.
I think the problem is the usage of cms (deprecated). Use pkcs7, that should carry a compatible version of der.

**Comment by RaitoBezarius** [comment]
I had multiple `der` in my tree
