### ISSUE TITLE
`pkcs1`: Document that it only accepts RFC 7468 textual encodings

### ISSUE THREAD

**Issue by str4d** [RustCrypto/formats#112]
The trait method for deserializing PKCS#1-encoded RSA private keys is documented as accepting PEM:

https://github.com/RustCrypto/formats/blob/2898d3949a3ab671d024f7381c979254d1b9fd0c/pkcs1/src/traits.rs#L29-L39

However, via the call graph we can see it actually uses the `pem-rfc7468` crate, which parses textual encodings that are a strict subset of PEM:

https://github.com/RustCrypto/formats/blob/2898d3949a3ab671d024f7381c979254d1b9fd0c/pkcs1/src/document/private_key.rs#L56-L57

https://github.com/RustCrypto/formats/blob/2898d3949a3ab671d024f7381c979254d1b9fd0c/pkcs1/src/lib.rs#L70

In particular, this makes the trait impl incompatible with legacy passphrase-encrypted OpenSSH keys:

```
   Unlike legacy PEM encoding [RFC1421], OpenPGP ASCII armor, and the
   OpenSSH key file format, textual encoding does *not* define or permit
   headers to be encoded alongside the data.  Empty space can appear
   between the pre-encapsulation boundary and the base64, but generators
   SHOULD NOT emit such any such spacing.  (The provision for this empty
   area is a throwback to PEM, which defined an "encapsulated header
   portion".)
```

The documentation for `FromRsaPrivateKey::from_pkcs1_pem` should be updated to clarify that it only accepts RFC 7468 textual encodings, not arbitrary PEM.

**Comment by str4d** [comment]
Ah, nice! That error case isn't quite sufficient on its own, as I need to check that the header present is in fact the encrypted PEM header, but that could be done with a wrapper (as if that error is returned, we know there is at least enough data to see the header).

**Comment by dwhjames** [comment]
@str4d, FYI, I added (https://github.com/RustCrypto/formats/pull/13) `Error::HeaderDisallowed` with exactly that use case in mind. Sorry, only just catching up on the comments over in https://github.com/str4d/rage/pull/261#discussion_r730388604
