### ISSUE TITLE
cms: add support for Authenticated-Enveloped-Data Content Type (RFC 5083)

### ISSUE THREAD

**Issue by KizzyCode** [RustCrypto/formats#1171]
This is a feature request to add support for the Authenticated-Enveloped-Data Content Type from [RFC 5083](https://www.rfc-editor.org/rfc/rfc5083.txt) for the `cms` crate.

I'm willing to create and submit a PR for this, if this fits into the intended scope of the `cms` crate 😊

**Comment by tarcieri** [comment]
Fixed in #1357 I believe
