### ISSUE TITLE
der_derive pulls in both syn 1.x and 2.x

### ISSUE THREAD

**Issue by jplatte** [RustCrypto/formats#1173]
It uses syn 2.x directly, but syn 1.x through `proc-macro-error`. `proc-macro-error` repo is [here](https://gitlab.com/CreepySkeleton/proc-macro-error) if you want to look at the state of `proc-macro-error` switching to syn 2.x. I don't think it's looking good, and it seems like you don't use it a ton, so using syn's builtin error handling functionality instead is what I would do if I had some time to work on this.

**Comment by tarcieri** [comment]
Yeah, that is unfortunate. I'm not sure what alternative you're proposing though... can you link to the relevant documentation? Does it provide similar error diagnostics?

**Comment by jplatte** [comment]
Unfortunately, syn provides no helpers for conveniently using the nightly-only diagnostics API when it's available if that's what you mean. When I find some time I can look into what exactly the crate does in terms of error reporting, to be able to propose alternatives.

**Comment by tarcieri** [comment]
I don't mean the nightly-only diagnostics API which it doesn't use AFAIK, just the error messages produced by `proc-macro-error`, which are quite informative as to the sources of errors.

If there's a major regression in UX and/or maintainability, I'd probably prefer to try to contact the author and see if they can get the crate updated.

**Comment by jplatte** [comment]
proc-macro-error is only special in that it uses the nightly API when users are on nightly anyways, and in that it makes collecting errors from multiple sources more convenient. Making errors point at specific parts of the code has been easy to do with `syn::Error` for ~ever.

**Comment by tarcieri** [comment]
> Making errors point at specific parts of the code has been easy to do with syn::Error for ~ever.

@jplatte again, can you link to the documentation for this?

**Comment by jplatte** [comment]
Sorry. The replacement for that is making your functions that should be able to "abort" return `syn::Result`, constructing a `syn::Error` in the error case (usually using `new_spanned` to specify a piece of syntax the error should be attached to) and bubbling it up. In can then be turned into a compile error at the proc-macro entry point or another appropriate place using `to_compile_error` or `into_compile_error`.

**Comment by tarcieri** [comment]
That would seem to involve quite a bit of boilerplate that `proc-macro-error` eliminates, no?

**Comment by jplatte** [comment]
Actually I wrote an article about this a while ago. It was written against syn 1.0, but the error handling hasn't changed in 2.0. https://blog.turbo.fish/proc-macro-error-handling/

**Comment by tarcieri** [comment]
Also do you have an actual example somewhere? I can't find it in the docs

**Comment by tarcieri** [comment]
I can try to look at this when I have some time but it's not going to be very high on my priorities list.

I know next to nothing about proc macro error handling which is why we're using `proc-macro-error` to make it easy, so I would really really appreciate some help

**Comment by jplatte** [comment]
Alright, I think I can actually spend a little bit of time on it now.
