### ISSUE TITLE
const-oid: `arbitrary` feature has dependency that requires rustc > MSRV

### ISSUE THREAD

**Issue by flihp** [RustCrypto/formats#1194]
With the `arbitrary` feature enabled `const-oid` currently pulls down the latest `1.2` release of the `arbitrary` crate. This crate requires MSRV `1.63` though the current `const-oid` docs claim support for `1.57`. This is currently causing the clippy workspace github action to fail. Possible resolutions include:
- bumping MSRV to `1.63` which, per the README.md requires a minor version bump
- possibly downgrading these dependencies (I've not tested this so it may not be possible)

#1182 works around this CI failure by disabling the relevant feature

**Comment by tarcieri** [comment]
`const-oid` is already MSRV 1.65 on `master` (0.10.x-pre), so this is only about the backported branch for 0.9.x.

Really I don't care about the old MSRV with `arbitrary` enabled. It's off-by-default, so it doesn't break current users or the advertised MSRV.

I would suggest just disabling `--all-features` for clippy on the 0.9.x branch.

**Comment by flihp** [comment]
Sounds good. #1182 already has the workaround you suggested. I just wanted to get this data preserved somewhere more visible so others don't trip over this the way I did.

**Comment by baloo** [comment]
Fixed in #1182
