### ISSUE TITLE
PrivateKeyInfo::try_from

### ISSUE THREAD

**Issue by salih-okur** [RustCrypto/formats#1227]
I am trying to give "3081...".asBytes() (as below) as parameter to PrivateKeyInfo::try_from but it return error everytime.
My variable let base64_str = "3081F7020101302C06072A8648CE3D0101022100FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF305B0420FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC04205AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B031500C49D360886E704936A6678E1139D26B7819F7E900441046B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C2964FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5022100FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551020101";

error thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Asn1(Error { kind: TagUnknown { byte: 51 }, position: None })'

Do you have any idea?

**Comment by tarcieri** [comment]
Well, for starters, if you're trying to decode bytes you need to give it actual bytes. What you have is hex (not Base64, despite the variable name). You need to decode the hex to bytes, then pass that.

However, if you do that, you'll encounter this:

```rust
Asn1(Error { kind: TagUnexpected { expected: Some(Tag(0x04: OCTET STRING)), actual: Tag(0x30: SEQUENCE) }, position: None })
```

The decoded ASN.1 structure looks like this:

```
PrivateKeyInfo SEQUENCE (6 elem)
  version Version INTEGER 1
  privateKeyAlgorithm AlgorithmIdentifier SEQUENCE (2 elem)
    algorithm OBJECT IDENTIFIER 1.2.840.10045.1.1 prime-field (ANSI X9.62 field type)
    parameters ANY INTEGER (256 bit) 1157920892103562487626974469494075735300861434152903141955336313088670…
  privateKey PrivateKey [?] SEQUENCE (3 elem)
    OCTET STRING (32 byte) FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC
    OCTET STRING (32 byte) 5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
    BIT STRING (160 bit) 1100010010011101001101100000100010000110111001110000010010010011011010…
  OCTET STRING (65 byte) 046B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C2964FE3…
  INTEGER (256 bit) 1157920892103562487626974469494075735299969552241357603424222590610685…
  INTEGER 1
```

I'm not sure where you got this key but it appears to be invalid. The schema we implement from [RFC5958](https://datatracker.ietf.org/doc/html/rfc5958#section-2) looks like this:

```
SEQUENCE {
       version                   Version,
       privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
       privateKey                PrivateKey,
       attributes            [0] Attributes OPTIONAL,
       ...,
       [[2: publicKey        [1] PublicKey OPTIONAL ]],
       ...
}

PrivateKey ::= OCTET STRING
                        -- Content varies based on type of key.  The
                        -- algorithm identifier dictates the format of
                        -- the key.
```

Wherever this key came from, it doesn't have an `OCTET STRING` for a `privateKey` field, but instead has a `SEQUENCE` consisting of two 32-byte `OCTET STRING`s followed by a `BIT STRING`. In a correctly formed key, these are typically serialized as ASN.1 DER first, then nested within the PKCS#8 document as an `OCTET STRING`.

Can you share more information on what generated this key?

**Comment by salih-okur** [comment]
I got it thank you for your help. Actually I want to generate secp256r1 key. The hex data ı shared include ec parameters of secp256r1 which are pointx,pointy,coefficient a and b and modulus( https://neuromancer.sk/std/secg/secp256r1 ). I just want to parse them by using  PrivateKeyInfo structure.

**Comment by tarcieri** [comment]
I'm not aware of a key format that looks like that.

The typical ASN.1 ECC private key format is defined in SEC1 and implemented by the `sec1` crate: https://docs.rs/sec1/0.7.3/sec1/struct.EcPrivateKey.html

The `p256` crate supports decoding this format for secp256r1, and when the `pkcs8` feature is enabled, can also support this format serialized to an `OCTET STRING` and wrapped in PKCS#8.

**Comment by salih-okur** [comment]
Thank you I will edit and try again
