### ISSUE TITLE
CMS: Can't parse CMS EnvelopedData DER generated by node-forge

### ISSUE THREAD

**Issue by bchmnn** [RustCrypto/formats#1231]
Disclaimer: I'm new to rust and crypto, therefore this my be a noobish question

When generating CMS EnvelopedData DERs using node-forge the result is not parsable using `cms::enveloped_data::EnvelopedData`.

The reason for this seems that the resulting ASN.1 differs slightly from the expected.

---

## In detail

The DER `MFQGCSqGSIb3DQEHA6BHMEUCAQAxADA+BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB+vzSEx8zurZJ9/YA7Qw3loBIEEFpJtVp0v4TDoA0nLkcvqoo=` looks like the following:

![image](https://github.com/digitalbazaar/forge/assets/34620799/240df556-9df3-4c9c-aff5-25dc212f4c95)
https://lapo.it/asn1js/#MFQGCSqGSIb3DQEHA6BHMEUCAQAxADA-BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB-vzSEx8zurZJ9_YA7Qw3loBIEEFpJtVp0v4TDoA0nLkcvqoo

Parsing it results in the following error:

`Error { kind: Noncanonical { tag: Tag(0xa0: CONTEXT-SPECIFIC [0] (constructed)) }, position: Some(Length(69)) }`

However, if we forth- and back-parse the same DER using `openssl::pkcs7`, a slightly different DER is created, `MFIGCSqGSIb3DQEHA6BFMEMCAQAxADA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB+vzSEx8zurZJ9/YA7Qw3lgBBaSbVadL+Ew6ANJy5HL6qK`:

![image](https://github.com/digitalbazaar/forge/assets/34620799/f57e1f93-f82a-468d-b413-f4a453d8240b)
https://lapo.it/asn1js/#MFIGCSqGSIb3DQEHA6BFMEMCAQAxADA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB-vzSEx8zurZJ9_YA7Qw3lgBBaSbVadL-Ew6ANJy5HL6qK

Parsing this "fixed" DER using `cms::enveloped_data::EnvelopedData` succeeds.

If we have a look at the DERs we can see, that the only difference is within the last tags, specifically: `A0 xx 04 xx` vs `80 xx`.

I created a small repo for reproducing my findings: https://github.com/bchmnn/node-forge-vs-rust-crypto.

---

## My questions here are
- Is this a bug in node-forge, not implementing the correct CMS RFC specs?
- Is it a relict of old obsolete CMS specs?
- Since OpenSSL accepts the DER, is it a bug in RustCrypto's CMS?

**Comment by carl-wallace** [comment]
The structure where this is failing is EncryptedContentInfo. In the CMS spec ([RFC5652](https://www.rfc-editor.org/rfc/rfc5652)), it is defined as:

```
      EncryptedContentInfo ::= SEQUENCE {
        contentType ContentType,
        contentEncryptionAlgorithm ContentEncryptionAlgorithmIdentifier,
        encryptedContent [0] IMPLICIT EncryptedContent OPTIONAL }
```

In the older PKCS7 spec ([RFC2315](https://www.rfc-editor.org/rfc/rfc2315)), it is defined as:

```
   EncryptedContentInfo ::= SEQUENCE {
     contentType ContentType,
     contentEncryptionAlgorithm
       ContentEncryptionAlgorithmIdentifier,
     encryptedContent
       [0] IMPLICIT EncryptedContent OPTIONAL }
```

So the issue is not a relic of an older spec, since the structures are the same. I think you may be thinking of the issue SignedData has, which is described in [section 5.2.1](https://www.rfc-editor.org/rfc/rfc5652#section-5.2.1) of RFC5652. 

The RustCrypto parser is failing due to the 0xA0 byte, which indicates constructed contents were found where primitive contents were expected. This is why the 0x80 byte version succeeds, i.e., the constructed bit is set in 0xA0 but not in 0x80. This is clearly a bug in the generating code. It appears to be emitting an EXPLICITly tagged encryptedContent field. At a glance, the bug appears to be passing true as the constructed parameter here: https://github.com/digitalbazaar/forge/blob/main/lib/pkcs7.js#L1134. The nested encoding there looks suspicious as well.  OpenSSL is tolerant of EXPLICIT tagging here, which some may see as a bug and others may see as a feature. That they fix the encoding and hold the right value on the re-encoding at least shows the wrong value bytes wouldn't be used.

The encryptedContent field aside, EnvelopedData and RecipientInfos are defined as:

```
      EnvelopedData ::= SEQUENCE {
        version CMSVersion,
        originatorInfo [0] IMPLICIT OriginatorInfo OPTIONAL,
        recipientInfos RecipientInfos,
        encryptedContentInfo EncryptedContentInfo,
        unprotectedAttrs [1] IMPLICIT UnprotectedAttributes OPTIONAL }

     RecipientInfos ::= SET SIZE (1..MAX) OF RecipientInfo
```

One could argue that all three implementations have a bug with regard to the recipientInfos field, since the minimum size for that field is 1 and this structure has 0.

```
 20   0:       SET {}
```

This is a difference with the PKCS7 spec though:

```
RecipientInfos ::= SET OF RecipientInfo
```

**Comment by bchmnn** [comment]
@carl-wallace 
Thank you very much for your answer and in-depth insights into the root cause of this issue.

Since `node-forge` is still used actively (~20M downloads per week), does it make sense to allow EXPLICIT tagging in the RustCrypto ecosystem as OpenSSL does?

I will also create an issue in the node-forge repo. I fear that this won't help much, since no commits have been pushed on the node-forge main branch since Mar 30, 2022 and there are currently 358 open issues (456 closed). Also: https://github.com/digitalbazaar/forge/issues/1046.

Are there any other low-effort possibilities to parse those broken DERs using RustCrypto that you can think of and that do not include parsing ASN.1 manually, a node-forge PR / fork, or RustCrypto PR?

**Comment by carl-wallace** [comment]
Whether or not to try to accommodate this in the derive crate is not my call (but generally trying to accommodate busted encoders is a can of worms). Offhand, I'm not sure what the effort would be to accommodate miscoded ContextSpecific tags. 

However, you could fairly easily derive a couple of structs for this use case if you are only targeting output from node-forge or could easily use an alternative decoder when dealing with node-forge output. These could be used alongside structs from the cms crate.

```rust
#[derive(Clone, Debug, Eq, PartialEq, Sequence)]
#[allow(missing_docs)]
pub struct EnvelopedDataNodeForge {
    pub version: CmsVersion,
    #[asn1(
    context_specific = "0",
    tag_mode = "IMPLICIT",
    constructed = "true",
    optional = "true"
    )]
    pub originator_info: Option<OriginatorInfo>,
    pub recip_infos: RecipientInfos,
    pub encrypted_content: EncryptedContentInfoNodeForge,
    #[asn1(
    context_specific = "1",
    tag_mode = "IMPLICIT",
    constructed = "true",
    optional = "true"
    )]
    pub unprotected_attrs: Option<Attributes>,
}

#[derive(Clone, Debug, Eq, PartialEq, Sequence)]
#[allow(missing_docs)]
pub struct EncryptedContentInfoNodeForge {
    pub content_type: ObjectIdentifier,
    pub content_enc_alg: AlgorithmIdentifierOwned,
    #[asn1(context_specific = "0", tag_mode = "EXPLICIT", optional = "true")]
    pub encrypted_content: Option<OctetString>,
}

#[test]
fn cms_bug() {
    let bug1 = hex!("305406092A864886F70D010703A04730450201003100303E06092A864886F70D010701301D060960864801650304012A04107EBF3484C7CCEEAD927DFD803B430DE5A01204105A49B55A74BF84C3A00D272E472FAA8A");
    let ci1 = ContentInfo::from_der(&bug1).unwrap();
    assert_eq!(ci1.content_type, const_oid::db::rfc5911::ID_ENVELOPED_DATA);
    let bytes1 = ci1.content.to_der().unwrap();
    let result1 = EnvelopedDataNodeForge::from_der(bytes1.as_slice());
    assert!(result1.is_ok());

    let bug1 = hex!("305406092A864886F70D010703A04730450201003100303E06092A864886F70D010701301D060960864801650304012A04107EBF3484C7CCEEAD927DFD803B430DE5A01204105A49B55A74BF84C3A00D272E472FAA8A");
    let ci1 = ContentInfo::from_der(&bug1).unwrap();
    assert_eq!(ci1.content_type, const_oid::db::rfc5911::ID_ENVELOPED_DATA);
    let bytes1 = ci1.content.to_der().unwrap();
    let result1 = EnvelopedData::from_der(bytes1.as_slice());
    assert!(result1.is_err());
}
```

**Comment by bchmnn** [comment]
@carl-wallace 
Again, thank you very much for your time in helping me out.

I can confirm that your solution is working like it was expected.

I'll leave this issue open for the maintainers to decide whether it is still relevant (also regarding your findings related to the minimum size of the RecipientInfos).

**Comment by tarcieri** [comment]
> but generally trying to accommodate busted encoders is a can of worms

I agree with this.

If you need to interop with something with a malformed encoding, I'd suggest using the [structs @carl-wallace provided above](https://github.com/RustCrypto/formats/issues/1231#issuecomment-1737359240).
