### ISSUE TITLE
der: Meanless validation after ASN.1 SET OF sort

### ISSUE THREAD

**Issue by zkonge** [RustCrypto/formats#1236]
https://github.com/RustCrypto/formats/blob/9fd2b44029565c98dfb6b3aa2c25d4727d735261/der/src/asn1/set_of.rs#L120C13-L120C21

**Comment by tarcieri** [comment]
I guess you're saying the validation can be removed since we now always eagerly sort SET OFs?

FWIW, we used to reject documents with invalid `SET OF` orderings but they occur frequently enough and other parsers don't reject them so we wound up removing the checks #625

**Comment by zkonge** [comment]
yes
