### ISSUE TITLE
Guide about authenticode

### ISSUE THREAD

**Issue by pkking** [RustCrypto/formats#1250]
Hi, im recently working on authenticode, and i have read https://github.com/RustCrypto/formats/pull/723 and https://github.com/RustCrypto/formats/pull/813, so im just wondering if there's some guide for creating a authenticode signatrue using this library :_)

Sorry if the ping disturbed any of you @roblabla

**Comment by baloo** [comment]
I've made an implementation in [goblin](https://github.com/m4b/goblin/blob/master/src/pe/authenticode.rs). 
Because goblin doesn't want to pull extra dependencies, there an external crate ([goblin-signing](https://github.com/RaitoBezarius/goblin-signing/blob/main/src/authenticode.rs)) that brings rust-crypto hashers in.

**Comment by pkking** [comment]
> I've made an implementation in [goblin](https://github.com/m4b/goblin/blob/master/src/pe/authenticode.rs). 
> Because goblin doesn't want to pull extra dependencies, there an external crate ([goblin-signing](https://github.com/RaitoBezarius/goblin-signing/blob/main/src/authenticode.rs)) that brings rust-crypto hashers in.
> 
> (That second crate is still a WIP, the intention is for it to move to https://github.com/nix-community eventually)

Thanks for your reply, will take a look :)

**Comment by baloo** [comment]
I've put up a PR rewriting the authenticode according to the spec.
https://github.com/m4b/goblin/pull/383

**Comment by pkking** [comment]
> I've put up a PR rewriting the authenticode according to the spec.
> https://github.com/m4b/goblin/pull/383
> 
> 

cool!

**Comment by tarcieri** [comment]
Seems like the question here is answered?
