### ISSUE TITLE
tls_codec: no support for `uint24_t`-prefixed variable length vectors

### ISSUE THREAD

**Issue by tnytown** [RustCrypto/formats#1277]
`tls_codec` is missing the `TlsByteSliceU24` and `TlsByteVecU24` types. These are useful in verifying Signed Certificate Timestamps, which contain some uint24 sized fields [in the`digitally-signed` component](https://datatracker.ietf.org/doc/html/rfc6962#section-3.2).

I've worked around this in `sigstore-rs` [by hacking together a partial implementation of `TlsByteVecU24`](https://github.com/trail-of-forks/sigstore-rs/blob/bf01ea268773a237869b5906623326dd7a6fe9a4/src/crypto/transparency.rs#L114-L152), but it'd be nice to have a proper one upstream. I'm more than happy to contribute this myself if it'd be helpful.

**Comment by franziskuskiefer** [comment]
Yes! I was waiting for #1330. I have to see if that get's in or if I just do one now.
Let's say we get a release out this week.
