### ISSUE TITLE
Addition of BER

### ISSUE THREAD

**Issue by Firstyear** [RustCrypto/formats#1382]
Hi there,

I was curious if there were plans or interest to add BER to in addition to DER?

**Comment by tarcieri** [comment]
We do plan on supporting a limited number of BER productions as needed to support certain cryptographic formats (a bit confusing in a library named `der`, but it's where we are).

See #779 as the current open issue for that.

#1321 added some preliminary work to allow for it.

Closing this in favor of #779.
