### ISSUE TITLE
const-oid: type for OIDs in DB

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/formats#1417]
The latest `const-oid` prereleases support two different types for representing OIDs: `ObjectIdentifier` and `ObjectIdentifierRef`, the difference being the former is owned and the latter uses a borrowed byte slice and has an associated lifetime.

Right now `const_oid::db` uses `ObjectIdentifier`. A disadvantage of this is the backing storage for each constant is a fixed-sized array (of size `DEFAULT_MAX_SIZE` which is currently 39), regardless of the actual serialized BER representation of the OID, which adds code size bloat and otherwise wastes memory.

There are two ways this could be addressed:

- `ObjectIdentifier` with a const generic size specific to the BER encoding for each database entry: the type is already const generic around a size, unfortunately sizing them differently has potential ergonomic issues as they will be treated as different concrete types by the compiler.
- `ObjectIdentifierRef` (see #1413) can wrap static byte slices. Unfortunately it comes with its own ergonomic issues in terms of being more limited regarding what is allowed in `match` expressions.

Perhaps the largest issue is the main thing we want to do with OIDs is compare them, and currently we support very clear comparisons via `match` expressions. These are only possible with `ObjectIdentifier`, and those are only ergonomic if they're all the same size.

Furthermore, making those ergonomic `match` expressions work requires using derived impls of `PartialEq`/`Eq`. You unfortunately cannot write impls of those traits which would make it possible / ergonomic to compare `ObjectIdentifier`s of different sizes or `ObjectIdentifier`/`ObjectIdentifierRef` without sacrificing those `match` ergonomics. See #1293.

`ObjectIdentifierRef` has its [own ergonomic problems in `match` expressions](https://github.com/RustCrypto/formats/pull/1413#discussion_r1607696455): byte slice newtypes can't be used with them at all. 

So, the question is: are the code size / memory savings which would come from switching the database to `ObjectIdentifierRef` worth it? (i.e. should we merge #1413 or similar PR?) Or should we just leave things as is with `ObjectIdentifier<DEFAULT_MAX_SIZE>`?

cc @baloo

**Comment by tarcieri** [comment]
In #1413 I suggested we should potentially split out the OID database into its own crate like `const-oid-db` so we can get `const-oid` to v1.0 more easily while still having time to experiment with various database representations.

We could potentially merge them back together once they're stable and we're happy with them.

**Comment by baloo** [comment]
Most of the issues bubble up when you try to integrates those API changes in the rest of the ecosystem.
I think it's easier to just experiment in a local checkout and a bunch of `[patch.crates-io]` when needed.
I don't think it's worth splitting the database.

**Comment by tarcieri** [comment]
I would mostly like to get to `const-oid` v1.0 because upgrades are extremely painful and it’s a somewhat foundational crate.

I think we’re there aside from questions like this about the database.

**Comment by tarcieri** [comment]
Going to stick with an owned `ObjectIdentifier`. We'll see if people end up complaining about the added bloat.
