### ISSUE TITLE
der: Compilation error when combined with `worker` and `rsa` crate for WASM target

### ISSUE THREAD

**Issue by mishazharov** [RustCrypto/formats#146]
# Reproducing [DER crate](https://github.com/RustCrypto/formats/) compilation failure
See this repo https://github.com/mishazharov/der-repro for a small test case to show the error

## Versions

```bash
$ rustc --version
rustc 1.56.0 (09c42c458 2021-10-18)
```

```bash
$ cargo --version
cargo 1.56.0 (4ed5d137b 2021-10-04)
```

## Platform
Kernel: 5.11.0-38-generic
Distro: #42~20.04.1-Ubuntu
Arch: x86_64

## Steps to reproduce

Run `wasm-pack build --no-typescript --release`.

## Error shown
```
   Compiling der v0.4.4
error[E0277]: can't compare `usize` with `()`
   --> /home/misha/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.4.4/src/encoder.rs:151:43
    |
151 |         if nested_encoder.finish()?.len() == length.try_into()? {
    |                                           ^^ no implementation for `usize == ()`
    |
    = help: the trait `PartialEq<()>` is not implemented for `usize`

error[E0277]: the trait bound `(): From<Length>` is not satisfied
   --> /home/misha/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.4.4/src/encoder.rs:151:53
    |
151 |         if nested_encoder.finish()?.len() == length.try_into()? {
    |                                                     ^^^^^^^^ the trait `From<Length>` is not implemented for `()`
    |
    = note: required because of the requirements on the impl of `Into<()>` for `Length`
note: required because of the requirements on the impl of `TryFrom<Length>` for `()`
   --> /home/misha/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.4.4/src/asn1/null.rs:46:6
    |
46  | impl TryFrom<Any<'_>> for () {
    |      ^^^^^^^^^^^^^^^^     ^^
    = note: required because of the requirements on the impl of `TryInto<()>` for `Length`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `der` due to 2 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

## Proposed fix
I did some basic testing and found that patching the encoder with the following line appeared to resolve it on v0.4.4, but I didn't get the chance to test it on master.
In https://github.com/RustCrypto/formats/blob/master/der/src/encoder.rs#L159
```diff
        Header::new(Tag::Sequence, length).and_then(|header| header.encode(self))?;

        let mut nested_encoder = Encoder::new(self.reserve(length)?);
        f(&mut nested_encoder)?;

+       let len: usize = length.try_into()?;
+       if nested_encoder.finish()?.len() == len {
-       if nested_encoder.finish()?.len() == length.try_into()? {
            Ok(())
        } else {
            self.error(ErrorKind::Length { tag: Tag::Sequence })
        }
```
I wanted to get some thoughts before opening a PR though because this seems like a bandaid fix. Am happy to open a PR though if the maintainers think this is worth fixing and the fix is acceptable!

Edit: Going to open one anyway because it's easy

**Comment by olivereanderson** [comment]
We also got this issue (when targeting `wasm32-unknown-unknown`) after upgrading from `rsa 0.4` to `0.5.0` here is the branch: https://github.com/iotaledger/identity.rs/tree/chore/upgrade-rsa-version-libjose.  Did anyone copy this ticket to the Rust repo already?

**Comment by mishazharov** [comment]
@olivereanderson not yet, was working on a reproduction here: https://github.com/mishazharov/formats/tree/der-repro-2

Since this appears to be more widespread I'll just copy the issue as is tonight and add more info as I find it.

**Comment by tarcieri** [comment]
I can possibly attempt to backport #147 to `der` v0.4.x if this is really a widespread issue

**Comment by olivereanderson** [comment]
@tarcieri if that would not be too much trouble for you then that would be appreciated.

**Comment by olivereanderson** [comment]
@tarcieri that seemed to fix our problem. Thank you very much!

**Comment by mishazharov** [comment]
Actually, this doesn't look like a compiler bug anymore. After doing a lot of reducing, it looks like https://github.com/rust-random/getrandom has many conditional includes which masks this bug on platforms which aren't `wasm32-unknown-unknown`. Will need to do more reducing to figure out what the ultimate cause is[^1], but I'll hold off filing an issue to the Rust repo because this doesn't seem like it's compiler related.

If anyone wants to keep up with my progress or look at the current state of the reduction, see https://github.com/mishazharov/formats/blob/der-repro-2/der/src/lib.rs

[^1]: Currently looks like `wasm-bindgen` but might be one of its deps
