### ISSUE TITLE
x509-cert: Only allow `Certificate`s to be constructed via either the builder or deserialization

### ISSUE THREAD

**Issue by str4d** [RustCrypto/formats#1486]
The `Certificate` type is currently completely transparent:

https://github.com/RustCrypto/formats/blob/e0c3e08bd5fb8ee9c30aed7de271e2a25db5d531/x509-cert/src/certificate.rs#L183
https://github.com/RustCrypto/formats/blob/e0c3e08bd5fb8ee9c30aed7de271e2a25db5d531/x509-cert/src/certificate.rs#L199-L203
https://github.com/RustCrypto/formats/blob/e0c3e08bd5fb8ee9c30aed7de271e2a25db5d531/x509-cert/src/certificate.rs#L119-L144

This enables arbitrarily-invalid `Certificate`s to be constructed. In particular, this means that the `P: Profile` generic parameter cannot be trusted; if a downstream API receives an `&CertificateInner<Rfc5280>`, they have _zero_ guarantee that it is actually valid under the RFC 5280 profile.

The `x509-cert` crate's public API should be altered to make `Certificate` (and all types below it) opaque, replacing direct field access with getter methods. This would then enable `Certificate`s to be correct-by-construction, by enforcing the relevant `Profile` in the builder or during deserialization.

**Comment by tarcieri** [comment]
@baloo I'd be interested in taking this one

**Comment by baloo** [comment]
Sure!

**Comment by baloo** [comment]
I'm not sure I follow what you're saying here.

Is this to serialize extensions without the OctetString?

**Comment by tarcieri** [comment]
@baloo well, mostly I thought it might be helpful to make it semantically clear and easily grep-able when custom extensions are being constructed
