### ISSUE TITLE
der: add GeneraString (or more) tag(s)

### ISSUE THREAD

**Issue by zkonge** [RustCrypto/formats#1511]
I also work with kerberos types.

Just like https://github.com/RustCrypto/formats/issues/1385#issuecomment-2060035303 mentioned, the `Tag::GeneralString` is required for convenience.

 It is mentioned in the https://www.oss.com/asn1/resources/asn1-made-simple/asn1-quick-reference/generalstring.html
> GeneralString is too general to be implemented, therefore it is not recommended.

So an independent `GeneralString` type is not needed, but tags in enum is still valuable.

Going a step further, we should implement more tags in `der::tag::Tag`, then the `AnyRef` could parse more types?

**Comment by tarcieri** [comment]
Adding `Tag::GeneralString` is fine.

> Going a step further, we should implement more tags in der::tag::Tag, then the AnyRef could parse more types?

I would prefer to keep additions motivated by concrete use cases, rather than adding complexity for "completeness".

**Comment by zkonge** [comment]
`GeneralString` is enough. Closed by #1512.

**Comment by Firstyear** [comment]
Thank you for this! It is a great help for us too :)
