### ISSUE TITLE
Add rfc2985 and rfc7292 to const-oid db for pkcs#9 and pkcs#12

### ISSUE THREAD

**Issue by juliusl** [RustCrypto/formats#1543]
It would be nice to add rfc2985 and rfc7292 which reference some common attributes such as "friendlyName" and "localKeyId" both of which are common pkcs#12 attributes.

**Comment by nemynm** [comment]
I can send something by the end of the week probably, if no one else is on it. Would you want one or two PRs?

**Comment by tarcieri** [comment]
It's fine to put them both in one

**Comment by nemynm** [comment]
I actually think rfc2985 is already present since https://github.com/RustCrypto/formats/pull/1248. I'll just add rfc7292 then. Unless I missed something.
