### ISSUE TITLE
x509-cert: base64 decoding is stricter than OpenSSL's

### ISSUE THREAD

**Issue by kornelski** [RustCrypto/formats#1548]
`Certificate::load_pem_chain(cert)` fails with "PEM Base64 error: invalid Base64" on this certificate. The same data is parsed by BoringSSL without issues.

```
cert = "-----BEGIN CERTIFICATE-----\nMIIDzTCCArWgAwIBAgIQCjeHZF5ftIwiTv0b7RQMPDANBgkqhkiG9w0BAQsFADBaM\nQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlc\nlRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTIwM\nDEyNzEyNDgwOFoXDTI0MTIzMTIzNTk1OVowSjELMAkGA1UEBhMCVVMxGTAXBgNVB\nAoTEENsb3VkZmxhcmUsIEluYy4xIDAeBgNVBAMTF0Nsb3VkZmxhcmUgSW5jIEVDQ\nyBDQS0zMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEua1NZpkUC0bsH4HRKlAen\nQMVLzQSfS2WuIg4m4Vfj7+7Te9hRsTJc9QkT+DuHM5ss1FxL2ruTAUJd9NyYqSb1\n6OCAWgwggFkMB0GA1UdDgQWBBSlzjfq67B1DpRniLRF+tkkEIeWHzAfBgNVHSMEG\nDAWgBTlnVkwgkdYzKz6CFQ2hns6tQRN8DAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lB\nBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwNAYIK\nwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb\n20wOgYDVR0fBDMwMTAvoC2gK4YpaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL09tb\nmlyb290MjAyNS5jcmwwbQYDVR0gBGYwZDA3BglghkgBhv1sAQEwKjAoBggrBgEFB\nQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzALBglghkgBhv1sAQIwC\nAYGZ4EMAQIBMAgGBmeBDAECAjAIBgZngQwBAgMwDQYJKoZIhvcNAQELBQADggEBA\nAUkHd0bsCrrmNaF4zlNXmtXnYJX/OvoMaJXkGUFvhZEOFp3ArnPEELG4ZKk40Un+\nABHLGioVplTVI+tnkDB0A+21w0LOEhsUCxJkAZbZB2LzEgwLt4I4ptJIsCSDBFel\npKU1fwg3FZs5ZKTv3ocwDfjhUkV+ivhdDkYD7fa86JXWGBPzI6UAPxGezQxPk1Hg\noE6y/SJXQ7vTQ1unBuCJN0yJV0ReFEQPaA1IwQvZW+cwdFD19Ae8zFnWSfda9J1C\nZMRJCQUzym+5iPDuI9yP+kHyCREU3qzuWFloUwOxkgAyXVjBYdwRVKD05WdRerw6\nDEdfgkfCv4+3ao8XnTSrLE=\n-----END CERTIFICATE-----"
```

The certificate is from Mozilla's CCADB: https://ccadb-public.secure.force.com/mozilla/PublicAllIntermediateCertsWithPEMCSV (their CSV has extra single quotes that I'm stripping before parsing)

**Comment by tarcieri** [comment]
This certificate appears to have mismatched line lengths, namely for whatever reason the first line appears to be 65 characters, while the others are 64.

We definitely implement a stricter PEM parser than most, following a relatively strict interpretation of RFC7468. Here's how the README of the [`pem-rfc7468`](https://github.com/RustCrypto/formats/tree/master/pem-rfc7468) crate describes it:

> This crate provides a strict interpretation of the [RFC 7468](https://datatracker.ietf.org/doc/html/rfc7468) rules, implementing MUSTs and SHOULDs while avoiding the MAYs, targeting the "ABNF (Strict)" subset of the grammar as described in [RFC 7468 Section 3 Figure 3 (p6)](https://datatracker.ietf.org/doc/html/rfc7468#page-6).

(We interpret "MAY" in the context of RFCs like this as effectively being deprecations of behaviors tolerated by older parsers)

Here is the relevant section of RFC7468:

https://datatracker.ietf.org/doc/html/rfc7468#section-2

>   Generators MUST wrap the base64-encoded lines so that each line
>   consists of exactly 64 characters except for the final line, which
>   will encode the remainder of the data (within the 64-character line
>   boundary), and they MUST NOT emit extraneous whitespace.  Parsers MAY
>   handle other line sizes. 

Note: we do have off-by-default support for other line sizes so long as they're consistent.

Supporting mismatched line sizes is not something that would be easily accommodated by our current implementation in `pem-rfc7468`, which has also been written in a constant-time manner for handling PEM documents containing private keys (see the [`Util::Lookup` attack](https://arxiv.org/pdf/2108.04600.pdf)). While that's not directly relevant for X.509, it does remain a design goal for `pem-rfc7468` in general, so what you're asking for here would be implementing some sort of separate "quirks" parser which tolerates mismatched line sizes, and using that for X.509.

I don't see us doing that, at least any time soon.

If you really need to support certificates of this nature, the `pem` crate implements a much looser parser. You can use that to parse the certificate to DER, and then parse the DER.

Re-encoding the certificate with a consistent 64 character width would also fix the problem.

I'll also leave this here: https://www.ietf.org/archive/id/draft-iab-protocol-maintenance-05.html
