### ISSUE TITLE
cms unused feature "pem"

### ISSUE THREAD

**Issue by balderk** [RustCrypto/formats#1557]
Hi,

The cms crate enables the "pem" feature on the der crate.
As far as i can tell, the "pem" functionality is only used by tests. It would be great if enabling of this feature would be moved to [dev-dependency]

**Comment by balderk** [comment]
It's lovely that this is fixed so quickly, but I think the "pem" feature also should be removed. 

Please correct me if I'm wrong.

**Comment by tarcieri** [comment]
It was?

**Comment by balderk** [comment]
I meant the ``"der"`` on line 18 and 20.

**Comment by tarcieri** [comment]
`der::` is used several places in the crate. We can probably get rid of the transitive feature activations for `alloc` and `std` though

**Comment by balderk** [comment]
I mean only in the Cargo.toml file. 
This feature on the der crate drags in atleast two crates. And as far as I can tell, it's not being used anywhere.

**Comment by tarcieri** [comment]
`der` is a hard dependency that's used all over the place:

```console
$ grep -R "der::" src | wc -l
      69
```

**Comment by balderk** [comment]
Sorry... I miss spoke. I ment the "pem" feature on the der and x509-cert crate.

**Comment by tarcieri** [comment]
Aah, ok: #1565
