### ISSUE TITLE
der: Custom error types in derive macros.

### ISSUE THREAD

**Issue by turbocool3r** [RustCrypto/formats#1559]
Currently `der_derive` only provides macros that implement `DecodeValue` trait with `Error` associated type set to `::der::Error`. It would be nice to have support for custom error types via an attribute as discussed in #1053.

~~# Current blocker~~

~~The problem is `der::Reader` lacks support for error types in its [`sequence`](https://docs.rs/der/latest/der/ trait.Reader.html#method.sequence), [`read_nested`](https://docs.rs/der/latest/der/trait.Reader.html#method.read_nested), [`decode`](https://docs.rs/der/latest/der/trait.Reader.html#method.decode) and [`context_specific`](https://docs.rs/der/latest/der/trait.Reader.html#method.context_specific) methods. I think each of these should gain an additional generic parameter for error type.~~

I have a patch almost ready so if this is ok, I will move on to create a PR.

Update: after some review I see generic parameters are already implemented in my previous PR 😄

**Comment by tarcieri** [comment]
Seems like we can close this now that #1560 is merged?

**Comment by turbocool3r** [comment]
Yes, closing it
