### ISSUE TITLE
Can the library encode a plain private key using pkcs8 to der/pem?

### ISSUE THREAD

**Issue by asmmo** [RustCrypto/formats#205]
Can the library encode a plain private key using `pkcs8` to `der`/`pem`?
Plz, if yes, let me know how.
Thanks in advance.

**Comment by tarcieri** [comment]
What do you mean by "plain private key"?

PKCS#8 keys all have algorithm-dependent formats, along with OIDs which identify the individual algorithms and their parameters.

What cryptographic algorithms are you interested in?

**Comment by asmmo** [comment]
The main algorithm of interest is ed25519.
And if you can explain a little about `OID`s and how to get them using `OPENSSL`, it will be highly appreciated.

**Comment by tarcieri** [comment]
There's support in the `ed25519` crate, but it hasn't been released yet: https://github.com/RustCrypto/signatures/blob/master/ed25519/src/pkcs8.rs

It would take some work to adapt it to the currently released version.

It should hopefully be out in a month or so.

**Comment by asmmo** [comment]
I see.
But are the other keys like `Bls12381` and `Sr25519` ... supported?
Is the `OID` parameter responsible for defining the algorithm for interest or what?

**Comment by tarcieri** [comment]
Yes, and there needs to be a related specification for how to encode the key.

For Ed25519, that's RFC8410: https://datatracker.ietf.org/doc/html/rfc8410#section-7

**Comment by asmmo** [comment]
Ok.
Plz, could you give a working example for any of the three keys or any key else? Do they follow the same way to be encoded?

**Comment by tarcieri** [comment]
I'm not aware of any such RFCs for those curves

**Comment by asmmo** [comment]
Ok. I will search for their specifications then will do the same thing in the code example of any well know key if you could provide one.

**Comment by tarcieri** [comment]
FYI, the latest release of the `ed25519` crate now supports PKCS#8:

https://docs.rs/ed25519/1.3.0/ed25519/pkcs8/struct.KeypairBytes.html

**Comment by tarcieri** [comment]
I'll close this noting that the `pkcs8` crate is agnostic to the specific algorithms it's used with. The `PrivateKeyInfo` struct has a `private_key` field which is encoded as an `OCTET STRING` and modeled as a byte slice which can contain arbitrary data.

Where appropriate we try to provide higher-level wrappers, such as in the `ecdsa`, `elliptic-curve`, `ed25519`, `sec1`, and `rsa` crates.
