### ISSUE TITLE
base64ct v1.2.0 cargo-feature issue

### ISSUE THREAD

**Issue by durgesh-pandey** [RustCrypto/formats#253]
While building the base64ct or any repo which depends on it, I get the following error:
error: failed to parse manifest at `/../../../../formats/base64ct/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest

Please have a look if this is due to a new Rust related speciifcation.

**Comment by tarcieri** [comment]
`base64ct` is a 2021 edition crate with an MSRV of 1.56, which we state throughout our documentation.

[As we state in our MSRV policy](https://github.com/RustCrypto/formats/tree/master/base64ct#minimum-supported-rust-version), we do not include MSRV in the crate’s SemVer guarantees, but restrict MSRV changes to minor versions.

If you would like to use `base64ct` with pre-2021 editions of Rust, use the following SemVer statement in your Cargo.toml:

```toml
[dependencies]
base64ct = “>=1, <1.2”
```
