### ISSUE TITLE
function or associated item not found in `Base64`

### ISSUE THREAD

**Issue by ArunGust** [RustCrypto/formats#27]
|
20 |     println!("{}", Base64::encode_string(&msg));
   |                            ^^^^^^^^^^^^^ function or associated item not found in `Base64`

**Comment by tarcieri** [comment]
I'm guessing this is in regard to the `base64ct` crate?

https://docs.rs/base64ct/1.1.0/base64ct/trait.Encoding.html#tymethod.encode_string

Note that method requires that the `alloc` feature of the crate is enabled
