### ISSUE TITLE
AlgorithmIdentifier needs to implement DerOrd trait

### ISSUE THREAD

**Issue by rod-chapman** [RustCrypto/formats#288]
Can the AlgorithmIdentifier type be modified to implement the DerOrd trait so that a SET OF AlgorithmIdentifier is allowed?

Are there any other types in this crate that should also implement DerOrd so that SET OF can be used with them?

**Comment by tarcieri** [comment]
Yes, it should be impl'd on any type that can potentially be used in a `SetOf`

**Comment by tarcieri** [comment]
I added a `ValueOrd` impl in #288, from which it should receive a blanket `DerOrd` impl.

Give it a try and if things are looking good I can cut a release.

Re: other types, I don't think there are cases where it would be useful to have a SET OF them. Please open another issue if you do happen to encounter one.
