### ISSUE TITLE
Problem declaring a SET OF a SEQUENCE that contains an ENUMERATED value

### ISSUE THREAD

**Issue by rod-chapman** [RustCrypto/formats#296]
Problem trying to declare a SEQUENCE that contains an ENUMERATED field. Code as follows:

#[derive(Enumerated, Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u32)]
enum EID {
e1 = 1,
e2 = 2,
e3 = 3
}

#[derive(Clone, Debug, Eq, PartialEq, Sequence, PartialOrd, Ord)]
pub struct E {
eid: EID,
b1: bool,
b2: bool,
}
impl OrdIsValueOrd for E {}

type SetOfE = SetOf<E, 2>;

Compiling says:
error[E0759]: decoder has an anonymous lifetime '_ but it needs to satisfy a 'static lifetime requirement
--> src/main.rs:83:39
|
83 | #[derive(Clone, Debug, Eq, PartialEq, Sequence, PartialOrd, Ord)]
| ^^^^^^^^
| |
| this data with an anonymous lifetime '_...
| ...is captured and required to live as long as 'static here
|
= note: this error originates in the derive macro Sequence (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by rod-chapman** [comment]
Here is a shorter and complete test case:

```use der::{Enumerated, Sequence};

#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Enumerated)]
#[repr(u32)]
enum EID {
    E1 = 1,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Sequence)]
pub struct E {
    eid: EID,
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by rod-chapman** [comment]
Looking at the output of "cargo expand" on that, I can see that Enumerated generates:
```
impl ::der::DecodeValue<'static> for EID {
    fn decode_value(
        decoder: &mut ::der::Decoder<'_>,
        length: ::der::Length,
    ) -> ::der::Result<Self> {
        <u32 as ::der::DecodeValue>::decode_value(decoder, length)?.try_into()
    }
}
```
but the Sequence macro for struct E generates
```
impl ::der::Decodable<'_> for E {
    fn decode(decoder: &mut ::der::Decoder<'_>) -> ::der::Result<Self> {
        decoder.sequence(|decoder| {
            let eid = decoder.decode()?;
            Ok(Self { eid })
        })
    }
}
```
but I am not sure I understand it. Is the use of 'static in the declaration of DecodeValue for EID to blame perhaps?

**Comment by rod-chapman** [comment]
I made a local clone of this repo, and tried changing the 'static to '_ in enumerated.rs

It seems to work, but I honestly don't know why...

Specifically:

'''diff --git a/der/derive/src/enumerated.rs b/der/derive/src/enumerated.rs
index 48242dc..e738af3 100644
--- a/der/derive/src/enumerated.rs
+++ b/der/derive/src/enumerated.rs
@@ -95,7 +95,7 @@ impl DeriveEnumerated {
         }
 
         quote! {
-            impl ::der::DecodeValue<'static> for #ident {
+            impl ::der::DecodeValue<'_> for #ident {
                 fn decode_value(
                     decoder: &mut ::der::Decoder<'_>,
                     length: ::der::Length
'''

**Comment by tarcieri** [comment]
@rod-chapman can you PR that? I assume the issue here is the lifetime is being propagated from the outer type, and so it fails when it isn't `'static`

**Comment by rod-chapman** [comment]
Note sure I've fully understood lifetimes (yet...) How do I "PR it"???

**Comment by tarcieri** [comment]
Never mind. I opened #367 with the changes.

**Comment by rod-chapman** [comment]
Thanks
