### ISSUE TITLE
`der` crate fails to emit implicit context-specific tags on `SET`

### ISSUE THREAD

**Issue by npmccallum** [RustCrypto/formats#322]
There is a bug with the generated DER somewhere in the `der` crate. I discovered this while writing a `pkcs10` crate. This causes the encoding tests to fail. Specifically, it fails to correctly emit the `IMPLICIT` tag modification of the `SET` in `CertReqInfo::attributes` (see tagged PR). Decoding works correctly.

The fix is probably simple, but I don't know enough about the structure of the `der` crate to find it easily. And since I'm not sure you actually want this PR, I didn't spend a lot of time on it. I'm willing to produce a patch if you point me in the right direction.

The following code triggers the bug:

```
#[derive(Clone, Debug, PartialEq, Eq, Sequence)]
pub struct Foo {
    #[asn1(context_specific = "0", tag_mode = "IMPLICIT")]
    pub bar: SetOfVec<Baz>,
}
```

Decoding of the above code works correctly. But encoding causes `SET` to be emitted without the context-specific `0` tag.

**Comment by tarcieri** [comment]
It's possible it's a bug in the custom derive macro. I'll take a look when I have some time.

**Comment by tarcieri** [comment]
#337 doesn't fix this problem in particular, but should make the various lowerings performed by the proc macro easier to compose and also easier to test.

I'd like to look into better options for how to test the expected output (currently it's just comparing to a `String`) but it should be fairly easy to write tests for various combinations of features at this point.

**Comment by bstrie** [comment]
I've confirmed that my PR at https://github.com/RustCrypto/formats/pull/349 addresses the original issue here.
