### ISSUE TITLE
Consider adding a new `Error` variant to express `AlgorithmIdentifier` parameters must be absent

### ISSUE THREAD

**Issue by mzohreva** [RustCrypto/formats#354]
Currently there is no way to communicate that `parameters` field in `spki::AlgorithmIdentifier` must not be specified. This is useful for e.g. Ed25519 keys where the algorithm OID contains all information needed and the RFC specifies that:
> the parameters MUST be absent.

Source: https://datatracker.ietf.org/doc/html/rfc8410#section-3

**Comment by tarcieri** [comment]
FWIW, the `ed25519` crate uses the `ParametersMalformed` variant for this:

https://github.com/RustCrypto/signatures/blob/0ed65a1dffea36bda55afdbeb586b3d6ad970dde/ed25519/src/pkcs8.rs#L74

(it could probably use a comment with that RFC citation, though)

**Comment by tarcieri** [comment]
There's unfortunately not support for public keys in the `ed25519` crate itself. That should probably get added.

**Comment by tarcieri** [comment]
I've added `ed25519::pkcs8::PublicKeyBytes` in https://github.com/RustCrypto/signatures/pull/455 which can be used to parse SPKI-encoded Ed25519 public keys.

It returns `spki::Error::ParametersMalformed` in the event there are any parameters present.
