### ISSUE TITLE
der: Question on CHOICE/enum and multi-tuple variants

### ISSUE THREAD

**Issue by orthecreedence** [RustCrypto/formats#517]
I'm starting to play around with `der` and noticed, as with all ASN.1 crates I've seen, that when describing `enum` with `CHOICE`, the variants are only allowed to have one tuple when using derive macros. I'm curious why that is. I'm very new to ASN.1, but from my understanding it's possible to have a choice with multiple structs within it. For instance couldn't something like 

```rust
enum Person {
    Firstname(String),
    FirstLast(String, String)
}
```

be represented by the following?

```asn.1
FirstLast ::= SEQUENCE {
    field0 UTF8String,
    field1 UTF8String }

Person ::= CHOICE {
     firstname UTF8String,
     firstLast FirstLast }
```

Is the idea to match the types in rust to the format describable by the schema files (in other words, `FirstName` would be a first-class struct in the rust code with two fields)? Or is there a technical reason for not doing this, like it would introduce some kind of ambiguity?

I'm mainly asking because I'm adding DER serialization to an existing system that makes use of enums with more than one tuple and trying to figure out if I can implement `Encodable`/`Decodable` directly for these using the format above (encode the tuples as an implied sequence) or if I should convert them to `struct`s with named fields instead.

Thanks for the library!

**Comment by tarcieri** [comment]
What you’re proposing, i.e. treating an enum variant with multiple fields as a `SEQUENCE`, could potentially work.

However, it would make the implementation of the proc macro a lot more complicated. Several of the attributes are designed to insert intermediate wrappers around the inner type of the variant, so in those cases it would need to insert an intermediate struct anyway.

In general I would suggest separating user-facing types from the ones used for encoding to avoid these sorts of problems.

**Comment by orthecreedence** [comment]
> What you’re proposing, i.e. treating an enum variant with multiple fields as a SEQUENCE, could potentially work.

Ok cool, at least I'm not way far off base.

> However, it would make the implementation of the proc macro a lot more complicated.

That makes sense. It shouldn't be too hard to do by hand.

> In general I would suggest separating user-facing types from the ones used for encoding to avoid these sorts of problems.

This is something I hadn't considered. My worry of doing this is the maintenance of having another layer of types and keeping them all in sync. Are there other advantages to this approach?

**Comment by tarcieri** [comment]
It's a pretty common pattern with serde types, or with protos and a library like Prost. It allows the encoding types to be "shaped" differently than the ones the end user actually works with, and enforce more invariants.

**Comment by orthecreedence** [comment]
Thanks, that makes sense!

**Comment by orthecreedence** [comment]
@tarcieri Do you have any examples off-hand of libraries that separate user types and encoding types? This increasingly seems like the best path to go down but the pattern is new to me (I'm coming from `serde_derive`) and I'd rather learn from others than blunder into a poorly-thought implementation. Thanks!

**Comment by tarcieri** [comment]
You can look at `cargo` for example. The lockfile parser has separate `Encodable*` types:

- https://github.com/rust-lang/cargo/blob/bb96b3a3e8dc434af81e5768240741711f011a73/src/cargo/core/resolver/resolve.rs
- https://github.com/rust-lang/cargo/blob/bb96b3a3e8dc434af81e5768240741711f011a73/src/cargo/core/resolver/encode.rs

**Comment by orthecreedence** [comment]
Awesome, thanks!
