### ISSUE TITLE
der: v0.6 release tracking issue

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/formats#526]
New versions of all of the `der` crate's dependencies are now released, which means it's possible to do another release of `der`/`der_derive`.

Ideally I think we can get any prospective breaking changes into the forthcoming release so the version in git can stay v0.6 as long as possible as opposed to having to immediately bump to v0.7.0-pre.

Here's a list of changes that would be nice to get into a v0.6 release of the `der` crate:

- [x] #304
- [x] #525
- [x] #604
- [x] #571
- [x] #625

**Comment by tarcieri** [comment]
All of the changes have now been implemented.

I am going to cut another round of prereleases, and if everything looks good cut a final v0.6 release soon.

**Comment by roblabla** [comment]
The 0.6 version has been cut, I suppose this can be closed?

**Comment by tarcieri** [comment]
Yep, thanks!
