### ISSUE TITLE
how to create a pair of keys RSA (2048)

### ISSUE THREAD

**Issue by nbari** [RustCrypto/formats#627]
Hi, first of all, many thanks for sharing this library, If possible could you please give an example of how to create a pair of ssh keys (private/public) mainly for RSA 2048?

**Comment by nbari** [comment]
Currently I am testing with this:

```rs
use rand::{rngs::StdRng, SeedableRng};
use ssh_key::{private::RsaKeypair, PublicKey};
use std::time::SystemTime;

fn main() {
    let d = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("Duration since UNIX_EPOCH failed");
    let rng = StdRng::seed_from_u64(d.as_secs());
    if let Ok(keys) = RsaKeypair::random(rng, 2048) {
        println!("{:?}", keys)
    }
}
```

`Carto.toml` dependencies:
```
[dependencies]
ssh-key = { version = "0.4", features = ["rsa", "alloc"] }
rand = "0.8.5"
```

But how could I format/print the public and private keys in OpenSSH format?

**Comment by tarcieri** [comment]
Please use `OsRng` or `rand::thread_rng` as your RNG. Seeding an RNG from the system clock is not secure.

There's some documentation on key generation here: https://docs.rs/ssh-key/latest/ssh_key/private/index.html#generating-random-keys

For RSA in particular you'll want to use `RsaKeypair::random`: https://docs.rs/ssh-key/latest/ssh_key/private/struct.RsaKeypair.html#method.random

```rust
use ssh_key::{private::RsaKeypair, rand_core::OsRng};

let rsa_2048_keypair = RsaKeypair::random(&mut OsRng, 2048)?;
```

**Comment by tarcieri** [comment]
> But how could I format/print the public and private keys in OpenSSH format?

Once you've generated a keypair, you need to turn it into an `ssh_key::PrivateKey`.

That's presently a little tricker than it needs to me:

```rust
use ssh_key::private::{PrivateKey, KeypairData};

let private_key = PrivateKey::try_from(KeypairData::from(rsa_2048_keypair))?;
let private_key_pem = private_key.to_openssh()? // get PEM-encoded `BEGIN OPENSSH PRIVATE KEY` string
let public_key_str = private_key.public_key().to_openssh()?;
```

If you use `PrivateKey::random`, it's a little more straightforward, but you can't pick the key size (it defaults to 4096):

```rust
use ssh_key::{Algorithm, PrivateKey, rand_core::OsRng};

let private_key = PrivateKey::random(&mut OsRng, Algorithm::Rsa)?;
```
