### ISSUE TITLE
MIN_KEY_SIZE to 1024 instead of 2048 (customisable) 

### ISSUE THREAD

**Issue by nbari** [RustCrypto/formats#628]
Is there a way to create RSA keys of 1024 as the minimum instead of 2048 or make it optional?

I am trying to create keys using Cloudflare workers, but with the default of 2048 I randomly get errors of exceeding CPU time for example: `Error: Worker exceeded CPU time limit.`

**Comment by tarcieri** [comment]
1024-bit RSA is considered insecure. It's been [phased out of TLS](https://blog.mozilla.org/security/2014/09/08/phasing-out-certificates-with-1024-bit-rsa-key) and will likely be dropped from future versions of OpenSSH.

If you really want to generate a 1024-bit RSA key you can do it with the [`rsa` crate](https://docs.rs/rsa). But before that you should make sure that RSA is the only option.

Algorithms like ECDSA and Ed25519 are much faster than RSA and much more secure than RSA-1024.

**Comment by nbari** [comment]
I manage to create the pair of keys using something like this:

```rs
let mut rng = OsRng;
let bits = 1024;
let priv_key = RsaPrivateKey::new(&mut rng, bits).expect("failed to generate a key");
let pub_key = RsaPublicKey::from(&priv_key);
```

But how to then use the keys with `ssh-key`? 

I tried:
```
let p = ssh_key::public::PublicKey::from(ssh_key::public::KeyData::Rsa(pub_key));
```

But get:

```
let p = ssh_key::public::PublicKey::from(ssh_key::public::KeyData::Rsa(pub_key));
   |                                                                            ^^^^^^^ expected struct `ssh_key::public::RsaPublicKey`, found struct `rsa::RsaPublicKey`
```

**Comment by tarcieri** [comment]
You'll need to do:

```
let ssh_rsa_public_key = ssh_key::public::RsaPublicKey::try_from(pub_key)?;
let ssh_public_key = ssh_key::PublicKey::from(ssh_key::public::KeyData::Rsa(ssh_rsa_public_key));
```

**Comment by nbari** [comment]
Many thanks
