### ISSUE TITLE
tls_codec: `no_std` support

### ISSUE THREAD

**Issue by franziskuskiefer** [RustCrypto/formats#64]
Allow building tls-codec with `no_std`.

> I now see this is a bit more `std`-dependent than I realized due to the extensive use of `std::io::{Read, Write}`.

_Originally posted by @tarcieri in https://github.com/RustCrypto/formats/pull/56#pullrequestreview-764378515_

**Comment by tarcieri** [comment]
I think we can close this as having initial `no_std` support in place
