### ISSUE TITLE
Use const generics in tls_codec array.rs

### ISSUE THREAD

**Issue by franziskuskiefer** [RustCrypto/formats#65]
Seems like something which would nicely be replaced with const generics, whenever you're ready to bump MSRV to 1.51.

_Originally posted by @tarcieri in https://github.com/RustCrypto/formats/pull/56#discussion_r716763640_

**Comment by tarcieri** [comment]
Note that this workspace is using `resolver = "2"`, which is necessary to avoid activation of `std`-dependent features in `no_std` crates when using `build-dependencies`/`dev-dependencies` with common dependencies.

That carries with it an MSRV of 1.51 anyway, so I'd say it would make sense to go ahead and change this.
