### ISSUE TITLE
Question on base64ct with Usage sample code for "Allocating (enable alloc crate feature) case"

### ISSUE THREAD

**Issue by z07** [RustCrypto/formats#671]
Hi, 

Excuse me, I'm sorry for asking a beginner's question like this. 
I'm trying to run the sample code for "Allocating" case on the document on base64ct-1.5.0 as following (with cargo 1.61.0 and with `[dependencies] base64ct = "1.5.0"` on my Cargo.toml).

``` Rust
extern crate alloc;

fn sample_usage() {
    use base64ct::{Base64, Encoding};
    let bytes = b"example bytestring!";
    let encoded = Base64::encode_string(bytes);
    assert_eq!(encoded, "ZXhhbXBsZSBieXRlc3RyaW5nIQ==");
    let decoded = Base64::decode_vec(&encoded).unwrap();
    assert_eq!(decoded, bytes);
}
```
The compler (stable-x86_64-pc-windows-msvc / rustc 1.61.0) put error on `encoding_string` with the message 
```
no function or associated item named `encode_string` found for struct `base64ct::Base64` in the current scope
function or associated item not found in `base64ct::Base64`rustc(E0599)
```
and warning on `Encoding` with the message
```
unused import: `Encoding`
```
I guess my code fails to enable alloc crate feature, and fails to reach `fn encode_string(input: &[u8]) -> String;` function, but so far I haven't specified my mistake and/or misunderstanding yet. 
I was wondering how to modify my code or Cargo.toml, or other settings to fix these errors above.
(The sample usage for "Heapless no_std usage" works well with my setting.)

Thank you so much for your help.

**Comment by tarcieri** [comment]
You need to enable the `alloc` crate feature:

```toml
[dependencies]
base64ct = { version = "1.5.0", features = ["alloc"]
```

**Comment by z07** [comment]
Thank you so much.
