### ISSUE TITLE
docs: Examples on how to connect the components of RustCrypto.

### ISSUE THREAD

**Issue by rjzak** [RustCrypto/formats#686]
There is some basic documentation on a per-crate level, such as https://docs.rs/pem-rfc7468/0.6.0/pem_rfc7468/. However, I haven't been able to find anything which shows how the various formats, algorithms, etc actually fit together.

For example, when you've got a key from the `p384` crate, how does that connect with the `pem` or `der` crates? The key has functions to make into bytes, and for some reason, I can't figure out how to make a PEM or DER from it without compiler errors, even when importing the traits `use p384::pkcs8::{DecodePrivateKey, EncodePrivateKey, EncodePublicKey, DecodePublicKey};`, or runtime errors where the der crate can't parse the bytes.

It's great there's *some* examples, but it feels like the docs were written by those who already are experts, leaving us newbies (or just me) stranded and lost. It'd be nice to see documentation and/or examples from a more complete view of RustCrypto.

**Comment by tarcieri** [comment]
We generally try to provide high-level APIs documented in the respective crates so you don't have to assemble things like `pem-rfc7468` yourself.

You're on the right track with:

```rust
use p384::pkcs8::{DecodePrivateKey, EncodePrivateKey, EncodePublicKey, DecodePublicKey};
```

The documentation is admittedly a bit lacking here:

- https://docs.rs/elliptic-curve/latest/elliptic_curve/struct.SecretKey.html#parsing-pkcs8-keys
- https://docs.rs/elliptic-curve/latest/elliptic_curve/struct.PublicKey.html#parsing-spki-keys

There's some better documentation in the RSA crate with code examples:

- https://docs.rs/rsa/latest/rsa/#pkcs1-rsa-key-encoding
- https://docs.rs/rsa/latest/rsa/#pkcs8-rsa-key-encoding

To understand your problem better, I need to know what specific key formats you're trying to work with and then I can help you find the appropriate methods to call.

**Comment by rjzak** [comment]
I'm trying to figure out how to export `p384` keys as PEM and DER for [Wasi-crypto](https://github.com/WebAssembly/wasi-crypto/blob/main/implementations/hostcalls/rust/src/signatures/ecdsa.rs). The RSA side already has it. I can see the traits for `p384`, but can't figure out how to use them. I'll check those links and see how far I get.

**Comment by tarcieri** [comment]
The example @carl-wallace gave works.

To serialize a private key, use the [`pkcs8::EncodePrivateKey`](https://docs.rs/pkcs8/latest/pkcs8/trait.EncodePrivateKey.html) trait impl on `SigningKey`.
