### ISSUE TITLE
x509-cert: support creating Certificate without additional variables

### ISSUE THREAD

**Issue by lumag** [RustCrypto/formats#700]
`x509-cert`'s `Certificate` struct can not be easily created in a separate function, as creating it requires several intermediate temporary variables, which are borrowed rather than being moved to the created struct. E.g. my first attempt stopped at borrowing `signature`, `basic_contraint` (for Extension's `extn_value`) and public key DER. I can probably solve the PK part by using newly implemented `TryFrom`, but for the rest additional work/suggestions would be required. E.g. it would be nice to allow using `BitString` in addition to `BitStringRef` for the signature field.

**Comment by tarcieri** [comment]
I've definitely been meaning to add a certificate builder type, as it's a blocker for [migrating the `yubhism` crate](https://github.com/iqlusioninc/yubihsm.rs) (which would hopefully free up the `x509` crate so we could start using that name).

I might have some time this weekend to look at that.

**Comment by lumag** [comment]
This would be great!

**Comment by baloo** [comment]
Could we close this one?

**Comment by tarcieri** [comment]
Fixed by #764
