### ISSUE TITLE
How can I generate OpenSSH keys ?

### ISSUE THREAD

**Issue by kosten** [RustCrypto/formats#729]
Hello!

I can't find any example for this case. Could somebody tell me, how can I do it ?

For example:
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb/aSKhiCp1GOwKck6oO6ERZYpGZaDcaLgrji9vILlTI1D8D...`

Thanks!

**Comment by tarcieri** [comment]
See https://docs.rs/ssh-key/latest/ssh_key/private/index.html#generating-random-keys
