### ISSUE TITLE
sec1: Trait DecodeEcPrivateKey not implemented for EcPrivateKey

### ISSUE THREAD

**Issue by csarn** [RustCrypto/formats#747]
I have a sec1 pem private key ("BEGIN EC PRIVATE KEY") that I want to convert to pkcs8 (for use with rustls).
`sec1` has a trait `DecodeEcPrivateKey`, that is even documented as "Parse an EcPrivateKey from a SEC1-encoded document".
So I assumed I would do 
```rust
use sec1::DecodeEcPrivateKey;
use sec1::pkcs8::{DecodePrivateKey, EncodePrivateKey};
let key = EcPrivateKey::from_sec1_pem(key).unwrap();
let key_pkcs8 = key.to_pkcs8_der().unwrap();
```
But rustc complains:

```
77 |     let p = EcPrivateKey::from_sec1_pem(key).unwrap();
   |                           ^^^^^^^^^^^^^ function or associated item cannot be called on `EcPrivateKey<'_>` due to unsatisfied trait bounds
   |
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/sec1-0.3.0/src/private_key.rs:62:1
   |
62 | pub struct EcPrivateKey<'a> {
   | ---------------------------
   | |
   | doesn't satisfy `EcPrivateKey<'_>: DecodeEcPrivateKey`
   | doesn't satisfy `EcPrivateKey<'_>: DecodePrivateKey`
   |
   = note: the following trait bounds were not satisfied:
           `EcPrivateKey<'_>: DecodePrivateKey`
           which is required by `EcPrivateKey<'_>: DecodeEcPrivateKey`
           `&EcPrivateKey<'_>: DecodePrivateKey`
           which is required by `&EcPrivateKey<'_>: DecodeEcPrivateKey`
           `&mut EcPrivateKey<'_>: DecodePrivateKey`
           which is required by `&mut EcPrivateKey<'_>: DecodeEcPrivateKey`

```
How am I supposed to use this crate and its traits? Is this an actual bug/missing feature or just insufficient documentation?

**Comment by csarn** [comment]
I couldn't get this working, but that might just be my inexperience. I solved my problem by calling out to openssl. It's ugly, but I can't spend too much time on this. Maybe I will visit this again in the future.

**Comment by tarcieri** [comment]
Ok, it should be pretty easy if you use the `pkcs8` crate directly. Let me know if you need any help.

**Comment by brocaar** [comment]
@tarcieri I got stuck on exactly this same and I found the this issue. An example would be very welcome. For RSA I have the following and I was hoping it would more or less the same for EC keys but that doesn't seem to be the case due to the error mentioned earlier in this issue:

```rust
use rsa::{
    pkcs1::DecodeRsaPrivateKey,
    pkcs8::{EncodePrivateKey, LineEnding},
    RsaPrivateKey,
};
```

```rust
    if pem.contains("RSA PRIVATE KEY") {
        let pkey = RsaPrivateKey::from_pkcs1_pem(pem).context("Read RSA PKCS#1")?;
        let pkcs8_pem = pkey.to_pkcs8_pem(LineEnding::default())?;
        Ok(pkcs8_pem.as_str().to_owned())
    } else {
        Ok(pem.to_string())
    }
```

I know that is quite an old issue, but I would appreciate any help. The documentation is (still) a bit confusing.

**Comment by tarcieri** [comment]
@brocaar sorry, I'm unclear what the problem is. You posted the `rsa` code, ostensibly because it's working? Can you post the code you're having problems with?

**Comment by brocaar** [comment]
I know that the example code is for RSA, I was hoping to do something similar for EC, e.g.

```rust
    if pem.contains("RSA PRIVATE KEY") {
        use rsa::{
            pkcs1::DecodeRsaPrivateKey,
            pkcs8::{EncodePrivateKey, LineEnding},
            RsaPrivateKey,
        };

        let pkey = RsaPrivateKey::from_pkcs1_pem(pem).context("Read RSA PKCS#1")?;
        let pkcs8_pem = pkey.to_pkcs8_pem(LineEnding::default())?;
        Ok(pkcs8_pem.as_str().to_owned())
    } else if pem.contains("EC PRIVATE KEY") {
        use sec1::{
            pkcs8::{EncodePrivateKey, LineEnding},
            DecodeEcPrivateKey, EcPrivateKey,
        };
        let pkey = EcPrivateKey::from_sec1_pem(pem).context("Read EC SEC1")?;
        let pkcs8_pem = pkey.to_pkcs8_pem(LineEnding::default())?;
        Ok(pkcs8_pem.as_str().to_owned())
    } else {
        Ok(pem.to_string())
    }
```

The `[DecodeEcPrivateKey](https://docs.rs/sec1/latest/sec1/trait.DecodeEcPrivateKey.html#)` trait is documented as

> Parse an EcPrivateKey from a SEC1-encoded document.

Like the original author of this issue, I'm wondering how to implement this as it errors with:

```
error[E0599]: the function or associated item `from_sec1_pem` exists for struct `EcPrivateKey<'_>`, but its trait bounds were not satisfied
    |
62  | pub struct EcPrivateKey<'a> {
    | ---------------------------
    | |
    | doesn't satisfy `<_ as TryFrom<PrivateKeyInfo<'a>>>::Error = Error`
    | doesn't satisfy `EcPrivateKey<'_>: DecodeEcPrivateKey`
    | doesn't satisfy `EcPrivateKey<'_>: TryFrom<PrivateKeyInfo<'a>>`
    |
    = note: the following trait bounds were not satisfied:
            `<EcPrivateKey<'_> as TryFrom<PrivateKeyInfo<'a>>>::Error = sec1::pkcs8::Error`
            which is required by `EcPrivateKey<'_>: DecodeEcPrivateKey`
            `EcPrivateKey<'_>: TryFrom<PrivateKeyInfo<'a>>`
            which is required by `EcPrivateKey<'_>: DecodeEcPrivateKey`
            `<&EcPrivateKey<'_> as TryFrom<PrivateKeyInfo<'a>>>::Error = sec1::pkcs8::Error`
            which is required by `&EcPrivateKey<'_>: DecodeEcPrivateKey`
            `&EcPrivateKey<'_>: TryFrom<PrivateKeyInfo<'a>>`
            which is required by `&EcPrivateKey<'_>: DecodeEcPrivateKey`
            `<&mut EcPrivateKey<'_> as TryFrom<PrivateKeyInfo<'a>>>::Error = sec1::pkcs8::Error`
            which is required by `&mut EcPrivateKey<'_>: DecodeEcPrivateKey`
            `&mut EcP    |
rivateKey<'_>: TryFrom<PrivateKeyInfo<'a>>`
            which is required by `&mut EcPrivateKey<'_>: DecodeEcPrivateKey`
```

So then the question is, how to use the `DecodeEcPrivateKey` trait if it is intended to parse a `EcPrivateKey` from SEC1 encoded document? A code example would be very helpful.

**Comment by tarcieri** [comment]
[As I already explained, you can't use `DecodeEcPrivateKey` trait to decode an `EcPrivateKey` type, and yes perhaps that reflects the names are bad](https://github.com/RustCrypto/formats/issues/747#issuecomment-1289471545). I am open to suggestions for better names, however keep in mind they implement a consistent naming scheme across the `sec1`, `pkcs1`, and `pkcs8` crates.

`EcPrivateKey` borrows from its input and is designed to be usable in `core` environments. However, you want to decode a PEM document, which needs to be decoded from PEM to DER first before `EcPrivateKey` can borrow from it.

@brocaar perhaps we can back up and ask what you are trying to do? Why are you using SEC1 keys in the first place? What are you trying to do with them?

These types are all low-level implementation details of legacy formats you probably shouldn't be working with directly.

For example, if you're just trying to parse an elliptic curve secret key from PEM, you should probably use [`elliptic_curve::SecretKey::from_sec1_pem`](https://docs.rs/elliptic-curve/0.13.4/elliptic_curve/struct.SecretKey.html#method.from_sec1_pem). But really you should avoid SEC1 PEM in modern applications and just use PKCS#8.

**Comment by brocaar** [comment]
> Why are you using SEC1 keys in the first place?

Because that is what `cfssl` outputs (https://github.com/cloudflare/cfssl), which is what most of the users of my project are using when generating keys. What I basically want to achieve is providing automatic compatibility with both. For RSA keys, the above code example does its job and I'm trying to implement the same for EC keys.

I'll look into the suggested `elliptic_curve` crate suggestion, thanks!

**Comment by brocaar** [comment]
@tarcieri unfortunately [elliptic_curve::SecretKey::from_sec1_pem](https://docs.rs/elliptic-curve/0.13.8/elliptic_curve/struct.SecretKey.html#method.from_sec1_pem) doesn't provide the solution as I believe it requires to specify the type of `C`. I'm dealing with user-input, so this type might not always be the same.

However, it seems that what I try to achieve was possible in the past using `sec1` (v0.2.1), see:

https://github.com/kazk/topk8/blob/main/src/lib.rs#L27

```rust
pub fn from_sec1_pem(pem: &str) -> Result<String, ConvertSec1Error> {
    use sec1::{
        pkcs8::{EncodePrivateKey, LineEnding, PrivateKeyDocument},
        DecodeEcPrivateKey,
    };
    let pkdoc = PrivateKeyDocument::from_sec1_pem(pem).map_err(ConvertSec1Error::Deserialize)?;
    let pkcs8_pem = pkdoc
        .to_pkcs8_pem(LineEnding::LF)
        .map_err(ConvertSec1Error::Serialize)?;
    let pkcs8_pem: &str = pkcs8_pem.as_ref();
    Ok(pkcs8_pem.to_owned())
}
```

Do you have any hints how the same can be done using the latest version of the `sec1` crate? A code-example would be very welcome, as I'm already stuck at this for a couple of hours.

**Comment by tarcieri** [comment]
You need to decode the PEM to DER first, then you can use `EcPrivateKey::from_der`.

There are many, many ways to decode PEM to DER. Here is one example:

https://docs.rs/elliptic-curve/0.13.8/src/elliptic_curve/secret_key.rs.html#222-234

```rust
       let (label, der_bytes) = pem::decode_vec(s.as_bytes()).map_err(|_| Error)?;

        if label != sec1::EcPrivateKey::PEM_LABEL {
            return Err(Error);
        }
```
