### ISSUE TITLE
DER: adding a field which is already DER encoded?

### ISSUE THREAD

**Issue by rjzak** [RustCrypto/formats#811]
Suppose I have a struct:

```rust

use der::Sequence;

#[derive(Sequence)]
struct MyThing {
   things: Vec<u8>,
   already_encoded: Vec<u8>,
}
```

How could I add bytes to `MyThing.already_encoded` that is a Vec that's from some other `der::Encode.to_vec()`? That is, I have something else already der-encoded (let's say `der(thing)`), and don't want to have an additional wrapper of der encoded vec of vec of bytes (let's say `der(der(thing))`).

**Comment by tarcieri** [comment]
I believe the `der::Document` type might work for this application
