### ISSUE TITLE
Any should have a value function similar to AnyRef

### ISSUE THREAD

**Issue by carl-wallace** [RustCrypto/formats#832]
When aligning some code with the new owned types APIs the lack of a value function on Any where there [is one](https://github.com/RustCrypto/formats/blob/master/der/src/asn1/any.rs#L54) on AnyRef was a problem. AnyRef also had a number of convenience functions that may be useful to add as well, i.e., ia5_string, printable_string, etc., but these are not essential. The latter can be seen [here](https://github.com/RustCrypto/formats/commit/72ef39a4ef39cd4dd8e31c653f00d7e520db8801#diff-d870f6fdad8c1ce92805b5f4efb99c604ad89a817fecc84c821e7c9aaa4ba8f8L98).

**Comment by tarcieri** [comment]
Fixed in #833
