### ISSUE TITLE
Empty copyright placeholder

### ISSUE THREAD

**Issue by alexanderkjall** [RustCrypto/formats#871]
The copyright placeholder in the apache file seems to be empty, this sometimes cause problems during the package review in debian:

https://github.com/RustCrypto/formats/blob/master/base16ct/LICENSE-APACHE#L189

**Comment by tarcieri** [comment]
Well damn, we're probably doing that all over the place.

I guess I can write a script to mirror the copyright info from the MIT license files (which we do generally keep up-to-date) into the Apache license files

**Comment by alexanderkjall** [comment]
Sorry for late answer, but maybe you could just write a sentence there about where the copyright information is? No need to make it complicated as far as I see it.

**Comment by tarcieri** [comment]
It's not that hard to write a script to mirror the information into the format the Apache license wants. I've just been busy.

**Comment by alexanderkjall** [comment]
It was pointed out to me that this copyright placeholder is a part of the instruction, and it's intentionally blank, I have misunderstood this for quite a while. I'm sorry for the error and hope that you haven't spent too much time on this.
