### ISSUE TITLE
Decode error for p256 public keys

### ISSUE THREAD

**Issue by Xynnn007** [RustCrypto/formats#903]
Hi, folks

## What did I meet?
When I use 
```rust
ecdsa::VerifyingKey::from_public_key_der(&pk_der_bytes[..])
```

to deserialize a p256-ecdsa public key from der bytes, there raises an error
```
unknown/unsupported algorithm OID: 1.2.840.10045.3.1.7"
```

I checked inside the public key and find that 
The oid inside the public key is `1.2.840.10045.2.1`, which is oid for ecPublicKey

Please, did I do anything wrong? Or it is because the oid assertion should allow two scenarios, s.t. the curve's oid or the ecPublicKey oid?

## More details

The test public key in pem is
```
-----BEGIN PUBLIC KEY-----
MFgwEgYHKoZIzj0CAQYHKoZIzj0CAQNCAASHtmpwjp/S2Cqruep1zFYzo/gYYJ+R
ZzirXW5cWO1c4ocoJXcvMxiDz9XU8P9g6HQeh1EkCOSNe5vwCZjGJNxf
-----END PUBLIC KEY-----
```

Thanks a lot!

**Comment by tarcieri** [comment]
How did you generate this key? It's malformed. Looking at the ASN.1:

```
$ cat | openssl asn1parse                                                                                          130 ↵
-----BEGIN PUBLIC KEY-----
MFgwEgYHKoZIzj0CAQYHKoZIzj0CAQNCAASHtmpwjp/S2Cqruep1zFYzo/gYYJ+R
ZzirXW5cWO1c4ocoJXcvMxiDz9XU8P9g6HQeh1EkCOSNe5vwCZjGJNxf
-----END PUBLIC KEY-----
    0:d=0  hl=2 l=  88 cons: SEQUENCE
    2:d=1  hl=2 l=  18 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   22:d=1  hl=2 l=  66 prim: BIT STRING
```

The first OID is correct: it identifies an elliptic curve public key. But the second OID is supposed to identify the elliptic curve. Instead it contains the same OID twice.

This is what a P-256 public key *should* look like:

```
$ openssl asn1parse -in p256-pub.pem
    0:d=0  hl=2 l=  89 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim: OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim: BIT STRING
```

**Comment by Xynnn007** [comment]
Oh, thanks! @tarcieri
