### ISSUE TITLE
x509-cert/der regression

### ISSUE THREAD

**Issue by lumag** [RustCrypto/formats#978]
I found a regression after upgrading to `x509-cert` 0.2.1 / `der `0.7.1. The attached certificate 
[test.txt](https://github.com/RustCrypto/formats/files/11144280/test.txt)  can be parsed prefectly with `x509-cert` 0.1 / `der` 0.6.1, but fails after upgrade with the following error:
> Error: Error { kind: Overlength, position: Some(Length(62)) }

I could not spot any obvious issue and the position seems lame (parsing `TbsCertificate` starting from byte 4 returns an error at position 29.

Reproducer (convert cert to DER for it to work):
```Rust

use x509_cert::certificate::Certificate;
use x509_cert::der::Decode;

fn main() {
    let name = std::env::args().skip(1).next().unwrap();
    let bytes = std::fs::read(name).unwrap();
    let parsed_cert = &Certificate::from_der(&bytes).unwrap();
    println!("{parsed_cert:?}");
}
```

**Comment by tarcieri** [comment]
git bisect is probably the easiest way to narrow down what change caused this. 

Offhand I'm not sure what it would've been. The only major changes to decoding I can think of were related to integer/serial number handling.

**Comment by lumag** [comment]
`git-bisect` points to a8a0b0440b5fca5ef9848a1811468c1157110e96 (#795)

**Comment by tarcieri** [comment]
Seems I guessed it then! cc @baloo

**Comment by lumag** [comment]
And going patch-by-patch (ugh), https://github.com/RustCrypto/formats/pull/795/commits/62bbe0abe2a84d47406c327713f1c13bcd9c14a9 is the problem.

**Comment by lumag** [comment]
And, I think I know the cause:
```diff
+const SERIAL_NUMBER_MAX_LEN: Length = Length::new(20);
```

**Comment by tarcieri** [comment]
Yeah, looks like a 21-byte serial number:

```
$ openssl x509 -in /Users/tarcieri/Downloads/test.txt -inform pem -text                                           130 ↵
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            84:ce:0b:f6:a0:fe:82:4e:e5:e5:06:ca:a8:9d:78:c6:15:01:62:57:71
```

I don't think it meets the criteria for 21-byte serial numbers to be allowed, which would be adding a leading zero so the resulting number is positive.

**Comment by lumag** [comment]
Well, quoting RFC 5280:
>    Note: Non-conforming CAs may issue certificates with serial numbers
   that are negative or zero.  Certificate users SHOULD be prepared to
   gracefully handle such certificates.

I think we should drop the SERIAL_NUMBER_MAX_LEN check from `SertificateNumber`. Instead this check should be a part of certificate builder.

**Comment by lumag** [comment]
In the end, rfc2459 did not contain such requirement. So we should be liberal in what we accept.

**Comment by baloo** [comment]
I thought we relaxed the check when parsing from DER (to allow any length) and enforced the 20bytes limitation on `new`?
Didn't I imagine that discussion?

**Comment by tarcieri** [comment]
See lots of previous discussion on #823, #826, and #831

**Comment by tarcieri** [comment]
@baloo you even quoted the exact same excerpt of RFC 5280: https://github.com/RustCrypto/formats/pull/823#issuecomment-1367709091

**Comment by tarcieri** [comment]
Seems the other PRs didn't actually fix handling of negative serial numbers then?

**Comment by baloo** [comment]
Looks like it fixed parsing of negative serials, but this one is just overlength?

**Comment by tarcieri** [comment]
Yeah I think you're right. And RFC5280 doesn't seem to provide specific guidance for this case.

**Comment by baloo** [comment]
That was the comment I was thinking about: https://github.com/RustCrypto/formats/issues/826#issuecomment-1369165851

**Comment by tarcieri** [comment]
also regardless, this seems like the wrong error, despite the name:

> Error: Error { kind: Overlength, position: Some(Length(62)) }

That error is intended for TLV framing bugs which made this somewhat confusing.

A better one might be `ErrorKind::Value` with `tag: Tag::Integer`, which would at least make it clearer where the error was occurring.

**Comment by tarcieri** [comment]
I improved the error in #988.

Gonna close this in favor of #984 and #987
