### ISSUE TITLE
x509-cert: support for non-RFC5280 profiles

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/formats#984]
This crate is described as implementing RFC5280, however we've had a number of requests to support various things which don't conform to the profile, namely serial numbers longer than 20 octets and negative serial numbers.

Some questions:

1. What profiles do we want to support?
2. How do we prevent non-RFC5280 certs from being used in contexts where they shouldn't? For example, how do we choose to implement [RFC5280 § 6.1](https://www.rfc-editor.org/rfc/rfc5280#section-6.1)? Should we add checks that must be remembered to be called? Use separate types for RFC5280 certs versus other profiles?
3. What is the impact on CRLs and OCSP?

**Comment by lumag** [comment]
1. This might be a tough question, especially if one starts to worry about minor differences broght up by small RFCs. E.g. IDN/IRI, Utf8String vs BMP, etc. After some thought, I'm really leaning towards just two: latest&greatest and everything else.
2. paragraph 6.1 explicitly `RECOMMENDS against including such checks`.
3. If they are handled by the same code, there is no impact. We will parse them in the same way, check the signatures, etc. CRL is a part of RFC 5280, so in theory 20 char boundary also applies there. But OCSP (RFC 6960) doesn't even mention the SerialNumber length. It just tells that ` serialNumber is the serial number of the certificate for which status is being requested.`

**Comment by tarcieri** [comment]
> paragraph 6.1 explicitly RECOMMENDS against including such checks.

@lumag if I understand correctly that's in the context of supporting a mixed RFC5280/non-RFC5280 mode, where it's suggesting you perform the same set of checks for all of the certificates, rather than selectively applying RFC5280 to some of the certificates.

However, in a pure RFC5280 mode, definitionally you do want those checks to ensure all certificates are valid according to the profile.

**Comment by lumag** [comment]
I think 6.1 tells that even if the app has such checks, they should be separate from path-validation algorithm.

**Comment by tarcieri** [comment]
Perhaps we could have something like:

```rust
pub struct Certificate<Profile = Rfc5280> { ... }
```

...which would allow different profiles to define different validation rules.

**Comment by tarcieri** [comment]
"Profile" is the term of art from RFC5280. It's used in the name of the RFC and throughout the body, including in comparisons to earlier X.509 profiles (e.g. in Section 6.1)

**Comment by carl-wallace** [comment]
Yeah, but also in more concrete sense in certificate policies. It's fine.
